### ISSUE TITLE
[Feature] Auto Tagging based on Performer/Studio/Other Tags

### ISSUE THREAD

**Issue by dn8sh6HY** [stashapp/stash#901] opened 2020-10-26 14:06 UTC
For example, if performer = "XXX" add tag "curvy"

**Comment by SpedNSFW** [comment] 2020-10-26 14:30
For performers in particular, I think it'd be best to allow you to tag them and then filter scenes by performer tags in addition to regular scene tags.

**Comment by echo6ix** [comment] 2020-10-31 09:32
I think this feature might be a duplicate of #675 and #121 and #809

**Comment by SpedNSFW** [comment] 2020-10-31 10:29
> I think this feature might be a duplicate of #675 and #121 and #809

I wouldn't say that this is a duplicate per se.

**Comment by venturevoom** [comment] 2020-12-18 17:47
Upvote here. And its not a duplicate of the mentioned Issues that deal with Tag Aliases in my opinion. 

My vision of that feature would be: 
a) A "Tag" Tab on Performers to add Tags to Performers.
b) A Config-Tab Task "Derive Scene Tags from Performer" or something like that, copying the Perfomer-Tags to the individual Scene or Gallery

**Comment by echo6ix** [comment] 2020-12-18 21:50
k, misunderstood. I think it may be a duplicate or have overlap with #120 #88 #828 (tldr performer tags and inherited tags)

Not trying to shoot it down (I like the idea), just trying to help organize the feature requests

**Comment by WithoutPants** [comment] 2024-02-23 03:50
This is more suited for a plugin.

**Closed by WithoutPants** 2024-02-23 03:50 UTC
