### ISSUE TITLE
[Feature] Hot Keys / Mouse mapping.

### ISSUE THREAD

**Issue by synsyn93** [stashapp/stash#308] opened 2020-01-03 19:42 UTC
**Describe the solution you'd like**
Set up a hot keys or mouse button mapping short cuts for various tasks. This could be expanded to other things such as rating scenes, apply tag X, or favoriting them etc.   Secondly if possible hot keys for the player, for example mouse scroll button to go forward or backwards in the scene.  I know that you can use arrow keys now to do this just wondering if it could be mapped to mouse or a key.

**Comment by Leopere** [comment] 2020-01-05 23:20
There's a discussion about this in a few places I believe already including Discord.  Some of the baseline suggestions are to just simply have similar hotkeys to YouTube L for skip forward J for skip backward K for pause and so on.  So far no progress has been made I believe in this except for one open PR.  I don't know if we have the hotkeys integrated into hover tooltips and so on.

#81  linked this one might be close-able by the owner or anyone feeling janitorial.

**Comment by WithoutPants** [comment] 2020-06-23 04:47
Closing as duplicate of #81

**Closed by WithoutPants** 2020-06-23 04:47 UTC
Labels: duplicate, feature
