### ISSUE TITLE
Docker stash missing modules for community scripts

### ISSUE THREAD

**Issue by disconnect5852** [stashapp/stash#4623] opened 2024-02-26 22:41 UTC
**Describe the bug**
after installing community scripts nearly all error with `ModuleNotFoundError: No module named 'stashapi'` and `ModuleNotFoundError: No module named 'pyvis'` etc...

**To Reproduce**
1. run stash as docker container, official stash docker image
2. install a communityscript, from "Plugins" tab, using source https://stashapp.github.io/CommunityScripts/stable/index.yml
3. try to run for example: "Dupe Marker Detector", "Tag Graph", 
4. look for errors in log

**Expected behavior**
no missing module errors

**Stash Version: (from Settings -> About):**

**Desktop (please complete the following information):**
 - OS: Ubuntu server X64
 - Browser firefox, brave
 - Version v0.24.3

**Additional context**
i know python is always a mess with dependencies, but i think these python modules would be nice to be pre installed in the official stash docker image, as probably we can install it manually with pip, but is should be done with every upgrade, which is not so nice.

**Comment by Maista6969** [comment] 2024-02-26 22:47
Duplicate of #4475 and #4300, addressed by #4488

More thoroughly addressed by the [full Dockerfile overhaul](https://github.com/feederbox826/stash-s6) on feederbox826 was/is working on

**Closed as completed** 2024-02-26 23:14 UTC
Labels: bug report
