### ISSUE TITLE
ffmpeg errors on import

### ISSUE THREAD

**Issue by rackstackjack** [stashapp/stash#40] opened 2019-04-05 17:25 UTC
ERRO[0266] ffmpeg error when running command

appear's to be occuring whenever importing files with weird characters - wrapping the command in quotations works fine. specifically '&' and brackets.

**Comment by bnkai** [comment] 2020-01-21 10:54
I can't reproduce that. Either it was fixed in the meantime or is not present in the linux version at least.
Tested by adding `[&` to the filename and completing scan and generate tasks.

**Closed** 2020-01-29 02:51 UTC
Labels: not-reproducible
