### ISSUE TITLE
[Bug Report] Scene Selection Not Persisting While Paging

### ISSUE THREAD

**Issue by stldude2001** [stashapp/stash#5341] opened 2024-10-04 14:21 UTC
**Describe the bug**
When you have multiple scenes selected that selection is not carried over when you go to the next page of scenes

**To Reproduce**
1. Go to Scenes page with either grid or list view
2. Click on check boxes to select multiple scenes
3. Notice that the "Play Selected", "Edit" and "Delete" buttons have appeared
4. Click the next page button at either the top or bottom of the page
5. Notice that the "Play Selected", "Edit" and "Delete" buttons have disappeared
6. Click the previous page button at either the top or bottom of the page
7. Notice that the previously selected scenes are no longer selected

**Expected behavior**
Multiple scenes should be able to be selected across multiple pages

**Stash Version: v0.27.0**

**Desktop (please complete the following information):**
 - OS: Mac OS Catalina
 - Browser Firefox 130.0.1

**Comment by DogmaDragon** [comment] 2024-10-04 16:41
Duplicate of https://github.com/stashapp/stash/issues/325

**Comment by DogmaDragon** [comment] 2024-10-04 16:42
The workaround at the moment is to select higher per page count.

**Comment by stldude2001** [comment] 2024-10-06 12:25
I disagree that this is the same issue. That issue is about having the "Select All" button select all scenes across all pages at the same time. This issue is about individual selection while going through pages.

This worked as I described in v0.26.2

**Comment by stldude2001** [comment] 2024-10-06 12:39
Ok it seems like the other issue is also talking about the edit functionality as well and I can't speak to that having working previously but the play button definitely did work previously

**Comment by DogmaDragon** [comment] 2024-10-06 12:55
You're right, there is a regression from the previous release version.

**Closed** 2024-10-07 00:20 UTC
Labels: bug
