### ISSUE TITLE
[Feature] Set performer image from current

### ISSUE THREAD

**Issue by QxxxGit** [stashapp/stash#1252] opened 2021-04-01 00:27 UTC
A nice QoL feature would be setting a performer image while we're viewing the image.

I suggest adding a "Set as Performer Image" menu option in the 3-dot menu where you can rescan or delete the image.

**Comment by peolic** [comment] 2021-04-01 12:44
Duplicate of #872?

**Closed** 2021-04-09 06:52 UTC
Labels: duplicate
