### ISSUE TITLE
[Feature] Allow video filters to be saved

### ISSUE THREAD

**Issue by tarzanboy76** [stashapp/stash#2161] opened 2021-12-22 02:14 UTC
**Is your feature request related to a problem? Please describe.**
When you use a filter for playing a video (eg, adjusting brightness or contrast), the settings for the filter cannot be saved.  The next time the video is played, the filters are automatically reset to their default position.  This limits their usefulness.

**Describe the solution you'd like**
It would be nice to be able to save the filter settings.  

**Describe alternatives you've considered**
There are no alternatives other than to apply filter adjustments each time a video plays.

**Additional context**
Adding a 'save' button would be useful.  However, ideally adjustments to video filters should save automatically to avoid the need for an additional step.

**Comment by kermieisinthehouse** [comment] 2021-12-29 04:54
Dupe of #1335 . Make sure to thumb that one up.

**Closed by kermieisinthehouse** 2021-12-29 04:54 UTC
