### ISSUE TITLE
[Bug Report] Plugin settings persist when not in use

### ISSUE THREAD

**Issue by QxxxGit** [stashapp/stash#4648] opened 2024-03-03 11:35 UTC
Plugin settings in `config.yml` persist when those settings no longer exist in the plugin's yml file.

For example, if I originally had `foo` as a setting, then later renamed that internal name to `bar`, `bar` is added to the config and `foo` is not removed.

**Comment by WithoutPants** [comment] 2024-03-03 22:36
I'm going to mark this as a Won't Fix. The settings in the plugin configuration are intended only as UI specifiers - a plugin can set settings that aren't named in the plugin configuration file by design. Removing a setting from the plugin configuration does not necessarily mean it should be removed from the `config.yml` file.

**Closed by WithoutPants** 2024-03-03 22:36 UTC
Labels: bug report
