### ISSUE TITLE
[Feature] Adding Profiles ( Users )

### ISSUE THREAD

**Issue by billouetaudrey** [stashapp/stash#5091] opened 2024-07-23 10:22 UTC
Hey,

Is it possible to add user / profile ? For let invited to only watch movie, and let only admin delete anything ?

Thanks

**Comment by DogmaDragon** [comment] 2024-07-23 10:30
Duplicate of https://github.com/stashapp/stash/issues/2337

**Closed by DogmaDragon** 2024-07-23 10:30 UTC
Labels: feature request, duplicate

**Comment by billouetaudrey** [comment] 2024-07-23 10:36
Sorry and thanks for your reply
