### ISSUE TITLE
[Feature] The legacy of tags by performers and studios

### ISSUE THREAD

**Issue by miltuss** [stashapp/stash#5285] opened 2024-09-22 08:06 UTC
It would be very practical if performers could inherit certain particular tags assigned to their media files. A tag inheritance system would be effective for better organization of performers and studios.

It's up to StashCore to do this, as legacy should disappear from performers and studios if it's also removed from the latter's media, it should be persistent to prevent the user from removing the tag if the performer's media or studio bear this heritage tag. the inheritance of certain specific tags could allow Three different phases:

1. An inheritance of a tag from a media to the performer/Studio
2. A legacy of a tag from the performer/Studio to the media
3. Or a two-way inheritance

This should only be enabled for specific tags, with method choice and persistence. Only StashCore could implement this effectively with the database.

**Comment by Gykes** [comment] 2024-09-22 17:04
https://github.com/stashapp/CommunityScripts/issues/410

From this post it looks like WP already said to you that this isn't going to be something that he intends to add to core and would be better suited for a plugin

**Comment by miltuss** [comment] 2024-09-22 22:32
I updated the FR, the function is much more complex to be integrated by a plugin. It is also essential for basic database organization with automated filtering optimization.

**Comment by Gykes** [comment] 2024-09-22 22:41
Why is it more complex to add as a plugin? If anything it's more complex as core as this seems like A LOT of backend work to make it fully functional.

Once again, WP has already said that he has no intention of adding something like this to the core of Stash and I don't know enough about to back end to make it functional. Even if I did, it would need to be approved by him anyway.

**Comment by DogmaDragon** [comment] 2024-09-23 05:10
Duplicate of https://github.com/stashapp/CommunityScripts/issues/410 and https://github.com/stashapp/stash/issues/4794

**Closed by DogmaDragon** 2024-09-23 05:10 UTC
Labels: feature request
