### ISSUE TITLE
[Feature] Reset Metadata Button

### ISSUE THREAD

**Issue by anonuser69** [stashapp/stash#2704] opened 2022-06-27 20:37 UTC
Due to some incorrect scraper matches using the Identify feature, my Stash instance now contains multiple videos with mismatching metadata.

Currently, I have to edit and remove data from all fields (title, URL, date, description etc.) manually.

I suggest adding a button to the operations menu titled "Reset Metadata", which will reset the metadata back to when it was first scanned.

A bonus would be to add an "Exclude from Identify" option so these don't get picked up and incorrectly matched again.

**Comment by SilentSpartan** [comment] 2022-06-28 07:39
The bonus exists already. It’s the organized button.

**Comment by Flashy78** [comment] 2023-04-27 17:06
@anonuser69 already created a feature request for Deidentify Scene https://github.com/stashapp/stash/issues/2494 even though the answer is simply delete the scene and rescan.
This one can be closed as the second part as the organized button already exists.

**Comment by DogmaDragon** [comment] 2023-04-27 17:23
Dupe of https://github.com/stashapp/stash/issues/2494

**Closed by DogmaDragon** 2023-04-27 17:23 UTC
Labels: feature request, duplicate
