### ISSUE TITLE
[Bug Report] studio can not save

### ISSUE THREAD

**Issue by WiiGe** [stashapp/stash#4447] opened 2024-01-10 03:01 UTC
**Describe the bug**
failed to save studio "HMN Works"
see: https://stashdb.org/studios/043b74bd-a51c-410b-8258-b28e612b106d

**To Reproduce**
1. Go to 'Studio'
2. Click on 'batch match'
3. Scroll down to 'HMN Works', click search result
4. try save the HMN Works
5. See error

**Screenshots**
see discord: https://discord.com/channels/559159668438728723/559159931505213440/1194223734408626306

**Stash Version: (from Settings -> About):**
v0.24.1
bd7d4ac7

**Desktop (please complete the following information):**
 - OS: TrueNAS Scale 23
 - Browser: Google Chrome Version 120.0.6099.199 (Official Build) (64-bit)

**Comment by WiiGe** [comment] 2024-01-10 03:01
![image](https://github.com/stashapp/stash/assets/8965675/1ed9c3f0-dcaa-4a2a-82ac-ba7077b1450e)

**Comment by DogmaDragon** [comment] 2024-01-10 03:49
The issue is specifically related to the different capitalization. 

If the studio is named `HMN Works`, the studio is scraped and saved as expected. 
If the studio is named `Hmn Works`, the error is returned. 

Reproduced on 95a2c8d.

**Comment by Maista6969** [comment] 2024-01-10 03:52
The same thing happens when renaming studios as well if the only differences are in casing

**Comment by AdultSun** [comment] 2024-01-10 05:35
I think this is the same bug I flagged here a couple months ago: https://github.com/stashapp/stash/issues/4229

The issue was closed, but according to the merged PR (#4248) it only addressed performers (names and aliases) and not studios. It looked like the same validation error affecting both object types. I tested in a few other places at the time but didn't see the same error outside of performers and studios:
> This bug does not appear to affect tags or movies, both of which require unique primary names. It also does not affect aliases for tags or studios which also must be unique.

**Closed** 2024-01-14 01:52 UTC
Labels: bug
