### ISSUE TITLE
[Feature] Clips Section

### ISSUE THREAD

**Issue by saturdaythrowaway** [stashapp/stash#671] opened 2020-07-17 01:46 UTC
I believe adding a separate section for clips (from Reddit/Imgur/Gfytube) would be useful as they can add loads of noise to the main Scene section. Additionally the ability to loop a clip would be convenient.

An additional library may be required as it would be easier to just drop any clips into it vs having to tag existing library items.

**Comment by WithoutPants** [comment] 2020-07-17 01:52
I'm hesitant to add an entirely new concept (with the associated schema tables, graphql schema and UI pages) when this feels like a pretty big overlap to the existing scenes concept. 

There is already a setting that allows looping of scenes under a given duration. 

I think the issue of small clips adding noise could be alleviated with some better filtering options - for example, saved/default queries - for filtering out videos under a given duration, or tagging such scenes with `clip`.

I think if we're to consider something like this, then it should have a distinct set of features that can't be met by the scenes subsystem.

**Comment by hyde231** [comment] 2020-07-17 05:47
> 
> 
> I'm hesitant to add an entirely new concept (with the associated schema tables, graphql schema and UI pages) when this feels like a pretty big overlap to the existing scenes concept.
> 
> There is already a setting that allows looping of scenes under a given duration.
> 
> I think the issue of small clips adding noise could be alleviated with some better filtering options - for example, saved/default queries - for filtering out videos under a given duration, or tagging such scenes with `clip`.
> 
> I think if we're to consider something like this, then it should have a distinct set of features that can't be met by the scenes subsystem.

+1 for quick filters, as I also see the problem of noise. Make this a system of user defined and permanently stored filters easily available as a quick drop down box, and everyone is able to define his/her own use cases.

**Comment by echo6ix** [comment] 2020-11-02 03:03
I landed here to see if anyone had ideas about how to handle clips, and yes, a "quick filters" idea sounds cool.

**Comment by cloudstrife11** [comment] 2020-11-02 05:30
What about Stash statspage are these little clips also added to the scenes. Maybe its better to add a clips stats also

**Comment by rg9400** [comment] 2020-11-02 15:19
I think having the concept of libraries could help here. We add paths and can set whether or not images/scenes get scanned, but if we are able to then associate those paths with libraries (a 1 library to multiple path relationship is what other media servers tend to use), then users could segregate out say a clips library from their scene library. Though I guess if someone comingles scenes + clips in the same folder, that may cause issues.

I agree that we do not need another object besides scenes to describe short clips, but the issue is mainly around organization. From my perspective, I may have a folder of gifs and webms and mp4s, but it's hard to properly pull those in Stash. I use Emby for this purpose since it allows me to set a library that contains both videos and images, and then I can simply navigate to the library before doing further filtering.

**Comment by secondfolder** [comment] 2020-12-30 11:20
Building on what @rg9400 said the notion of folders/collections could be one way to deal with this: https://github.com/stashapp/stash/issues/1029

**Comment by secondfolder** [comment] 2020-12-30 12:20
Alternatively what about instead of adding a clip specific view a new combined Scenes and Images view was added instead that could be easily filtered to show media under a certain duration (made more straightforward with default/saved filters)? This would allow you to have gifs and short clips show up in the one view, not require a separate entity in the DB, and provide a more generic/general purpose solution which should be helpful in a variety of other situations as well: https://github.com/stashapp/stash/issues/1030

**Comment by CuddleBear92** [comment] 2021-06-03 19:44
Couldn't clips be added to the image section as it makes more sense.
Also such a feature should have a duration filter, sorting any clips shorter than the set duration as a clip instead of a scene.

**Comment by yoshnopa** [comment] 2023-05-19 07:48
After the merge of my code #3583 for support of short clips/gifs in the image section, the closure of #926 and the possible combination with saved filters, it should be considered whether this ticket can be closed. Maybe those (still) interested in it could make a point if there is anything still missing?

**Comment by rg9400** [comment] 2023-05-21 18:04
> After the merge of my code #3583 for support of short clips/gifs in the image section, the closure of #926 and the possible combination with saved filters, it should be considered whether this ticket can be closed. Maybe those (still) interested in it could make a point if there is anything still missing?

I have been migrating to this, and it looks to be meeting my usecase perfectly. I noticed two things

1. The Wall view does not have sound, but some clips may have sound. Can that be added like how it works on the Scene view (maybe with a similar setting to enable/disable it).
2. A variety of shorter clips and gifs especially will not generate previews if Clip Previews is enabled. I can share the output, but I just assume gifs are not supported, and short clips will not make sense to have previews. Should those be excluded?

**Comment by yoshnopa** [comment] 2023-05-22 07:12
About other not supported previews, that should not happen. Maybe you can pin down a common format?
Otherwise, yes, give me the output of the generation process, I'll look into that.

**Comment by yoshnopa** [comment] 2023-07-11 08:29
As the requested Issues were resolved and no further issues/feedback came up, I would suggest the closure of this ticket @WithoutPants @saturdaythrowaway

**Closed** 2024-08-30 03:42 UTC
