### ISSUE TITLE
[Bug Report] Performers disambiguation not visible on Scenes Edit tab

### ISSUE THREAD

**Issue by Nuriel2** [stashapp/stash#5263] opened 2024-09-15 12:10 UTC
**Describe the bug**
Performers disambiguation is not visible in the scenes edit tab

**To Reproduce**
1- create a performer and populate the disambiguation field
2- add the performer to a Scene
3- go to the Scene Edit tab, check whether you can see the disambiguation value on the performer

**Expected behavior**
Performer name and disambiguation should be visible.

**Screenshots**
![Screenshot_from_2024-08-16_20-24-01](https://github.com/user-attachments/assets/094a47d5-6779-4333-9f89-253375a89aef)
![Screenshot_from_2024-08-16_20-21-56](https://github.com/user-attachments/assets/441362d0-c88c-43c8-a6aa-0183931efc79)

**Stash Version: (from Settings -> About):**
v0.26.2-63-ga94bf29b

**Desktop (please complete the following information):**
 - OS: Ubuntu 24.04
 - Browser: Firefox
 - Version: N/A

**Smartphone (please complete the following information):**
 - Device: N/A
 - OS: N/A
 - Browser: N/A
 - Version: N/A

**Additional context**
The disambiguation field is visible in the Scenes details tab. Only the Edit tab is affected.

**Comment by feederbox826** [comment] 2024-09-15 17:56
As noted in the discord, the CSS rule
https://github.com/stashapp/stash/blob/c9f76a01c5c24376cf91757334600c34276d6a6c/ui/v2.5/src/components/Performers/styles.scss#L180-L186

breaks it since `color` is applied to the text, blending it with the background

**Comment by feederbox826** [comment] 2024-09-15 17:57
possibly dupe of https://github.com/stashapp/stash/pull/5246

**Comment by feederbox826** [comment] 2024-09-15 18:07
confirmed fixed in 5246

**Comment by WithoutPants** [comment] 2024-09-15 23:26
Fixed in #5246

**Closed by WithoutPants** 2024-09-15 23:26 UTC
Labels: bug report
