### ISSUE TITLE
[Feature] Option to add performers to markers

### ISSUE THREAD

**Issue by escargotbuffed** [stashapp/stash#4194] opened 2023-10-12 02:40 UTC
In markers it is now possible to filter by performers who are in a scene. However, I think it would be interesting to link a performer only to the markers in which she appears, making it possible to see the markers filtered by all the moments in which a performer appears.
Currently, linked only to the scene, when I filter by performers in the markers, other performers appear different from the one I filtered because they are in the same scene.

**Comment by echo6ix** [comment] 2023-10-25 19:36
I like this.

What would be the best way to populate the performers upon creating a marker?
1. Leave the performer field blank and the user adds the names
2. Leave the performer field blank, but add an "Inherit" button that that populates the field with the scene performers.
3. Automatically inherit the performer's from the scene (and the user can remove performer's that don't belong)
    - Pros:
      - Efficiency. It's easier to remove performer's than add them
    - Cons:
      - Potential errors. Automatically inheriting the performers opens up to potentially incorrect marker metadata if the user isn't mindful of what was inherited in the field, which is a risk for scenes with a lot of performers (ie. movies)

Maybe option 2 is the best compromise.

**Comment by echo6ix** [comment] 2023-10-25 20:21
Turns out this is a duplicate of https://github.com/stashapp/stash/issues/765

**Comment by DogmaDragon** [comment] 2023-10-31 00:03
Dupe of https://github.com/stashapp/stash/issues/765

**Closed** 2023-10-31 00:04 UTC
Labels: feature request, duplicate
