### ISSUE TITLE
[Bug Report] Created markers are not directly shown after creation

### ISSUE THREAD

**Issue by d3f113** [stashapp/stash#2520] opened 2022-04-18 11:40 UTC
**Describe the bug**
When creating a marker in a scene, it is nit shown. After refreshing the website, all created markers are showm

**To Reproduce**
1. Go to a scene
2. Click on marker and enter data needed and click on create
3. no marker is shown, just after refreshing the page

**Expected behavior**
The markers should be visible like after refreshing the site

**Stash Version: (from Settings -> About):**
0.14.0

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser safari
 
**Smartphone (please complete the following information):**
 - Device: iPad Air 4

**Comment by WithoutPants** [comment] 2022-04-18 23:20
Duplicate of #2500.

**Closed by WithoutPants** 2022-04-18 23:20 UTC
Labels: bug, duplicate
