### ISSUE TITLE
[Bug Report] Image Wall Margin is set to 2px but displays 0px.

### ISSUE THREAD

**Issue by jala528** [stashapp/stash#5483] opened 2024-11-17 21:55 UTC
**Describe the bug**
Image Wall Margin setting is set to 2px, but the image wall displays 0px between each image. To fix, I have to go into the settings, erase the "2", add a "02", then confirm. On relauch it will reset itself back to falsely saying it's at 2px but actually be at 0px. 
Trying to set it to "2" or "02" within the config.yml file does not fix it.

**To Reproduce**
0. Nothing to exactly reproduce, it happens on launch. The only fix I know gets reset on relaunch.
1. Go to Interface Settings.
2. Click on Edit [Image Wall Margin]
3. "2" is displayed. Backspace so the "0" appears.
4. Add a "2" alongside the "0".
5. Fixed
6. Broken on Quit.

**Expected behavior**
Launching the exe should remember my settings.

**Screenshots**

![0](https://github.com/user-attachments/assets/be8e9ed0-bdc6-47af-bca9-c6195394e630)
![1](https://github.com/user-attachments/assets/01d87b12-d56c-4dba-a3d4-5c5ccd258c35)
![2](https://github.com/user-attachments/assets/409f2b46-b0c9-450f-a320-f15da4ca7957)
![3](https://github.com/user-attachments/assets/3361c887-2b90-4578-b578-7cb4dc4ec997)
![4](https://github.com/user-attachments/assets/d1800e3f-8e87-472b-b123-d4921dd24f14)

**Stash Version: v0.27.2**

**Desktop (please complete the following information):**
 - OS: Windows 11 version 23H2
 - Browser: Edge
 - Version: 131.0.2903.51 (Official build)

**Comment by Gykes** [comment] 2024-11-17 22:12
Unable to replicate this on Dev version on docker. 

Do you have any themes or plugins that could be messing with those settings?

**Comment by jala528** [comment] 2024-11-17 22:17
I have neither of those enabled. Just in case, JavaScript status does not matter either.

**Comment by Gykes** [comment] 2024-11-17 22:33
Hmm, even on my V27.2 (Still docker) I can't reproduce. Not sure why that's happening.

**Comment by Gykes** [comment] 2024-11-17 22:45
Okay, perhaps someone with a windows StashServer can help try and replicate. Until I find a way to track it down I can't help, sorry :(

**Comment by feederbox826** [comment] 2024-11-18 20:57
Can't replicate on windows v0.27.2

**Comment by feederbox826** [comment] 2024-11-18 20:58
If you have **any** plugins or custom css, disable it.

**Comment by jala528** [comment] 2024-11-18 21:00
I do not have those enabled.

**Comment by feederbox826** [comment] 2024-11-18 21:01
Then I'm not sure what is interfering with stash. the 02 should auto-correct into just `2` in the UI

**Comment by WithoutPants** [comment] 2024-11-21 02:46
Managed to reproduce this. It's occurring because the stash server is saving the UI config numeric fields as strings, and these aren't being converted correctly in the UI. The `Gallery` control is erroring because it is being provided a string instead of a number, and sets the margin to 0. This gets fixed by setting the value in the UI because it sets the numeric value in the browser, but when it reloads the config again, the correct value is lost.

**Closed** 2024-11-21 21:27 UTC
Labels: bug report
