### ISSUE TITLE
text file support and text input for stories

### ISSUE THREAD

**Issue by binarygeek119** [stashapp/stash#158] opened 2019-10-25 00:41 UTC
i like to see the support of txt files and a way to input new text (stories)

this would work by 
clicking new story will take you to a page for importing text copy and paste it in then click save
when it saves it would create a simple .txt

.txt files
when the scan see a new .txt file then it will add them auto by scanning

a sample if a txt file for some add functionality

story.txt

`
%% comment will not display after this tell next line    

%author%=the author %% will apply to metadata in stash   
 
%site%=site.com %%where the story come from    

%storyurl%=https://site.com/story.html %% click able to see story post

%tiltle%=name of story %% will apply to metadata in stash

%description%= this si a description of the story %% this applys to story page under title

%start% %% says the start of the story 

%part%=1 %% for next part this be for series to go the next part with out going back to stories page could be 1 to ∞

%end% %%this test stash the end of the story
`
![Untitled-1](https://user-images.githubusercontent.com/47513721/67534752-3ae29a80-f695-11e9-9a15-c2588dd5d1ff.jpg)

also i know playboy isnt the best example for a text story

**Comment by WithoutPants** [comment] 2019-10-25 00:47
Largely duplicates #14

**Comment by binarygeek119** [comment] 2019-10-26 23:09
i also like a way of uploading a image for a cover. a nice long term support feature would be able to generate a cover from title 
maybe have a template where you could upload a background image for it and pick a font 
for when there no covers

**Comment by Leopere** [comment] 2019-10-27 22:46
Ebooks is a hugely complex and horrible thing to have to deal with I don't recommend that we pursue this.  For some reason, even the Caliber guy is willing to maintain an entire dead programming language (Python 2.x) rather than have to rewrite the whole ebook program.  This would be an awesome feature to add but just doesn't feel like it's within scope.

**Comment by Leopere** [comment] 2019-10-27 22:50
This is technically a duplicate of #14 so lets explore this conversation there.

**Closed by Leopere** 2019-10-27 22:50 UTC
Labels: duplicate, feature, investigate
