### ISSUE TITLE
[Feature] Add search option in settings

### ISSUE THREAD

**Issue by David-Maisonave** [stashapp/stash#5499] opened 2024-11-21 21:21 UTC
**Is your feature request related to a problem? Please describe.**
I was trying to figure out how to import json (exported) data, but I couldn't find the option in the settings.
Programs with many options will sometimes have a search button that will help the user find the option.

**Describe the solution you'd like**
Add search button option to the settings menu, which would allow users to find location of options.

**Screenshots**
### Example FireFox settings menu with search option.
![Screenshot 2024-11-21 161223](https://github.com/user-attachments/assets/05a16166-72ad-41a9-b5e4-eb402fb6cd21)

### Example usage FireFox finding settings associated with keyword **password**.
![Screenshot 2024-11-21 161833](https://github.com/user-attachments/assets/54d941bb-a18b-45d1-b063-2eba6202cdba)

**Comment by DogmaDragon** [comment] 2024-11-22 00:02
Duplicate of https://github.com/stashapp/stash/issues/1246

**Closed by DogmaDragon** 2024-11-22 00:02 UTC
Labels: feature request
