### ISSUE TITLE
[RFC] Page Title Elements Schema Proposal

### ISSUE THREAD

**Issue by jeremymeyers** [stashapp/stash#1561] opened 2021-07-08 02:45 UTC
*### Scope*
To define how <title> elements should be generated for Stash pages.  These tables are not currently comprehensive and are instead intended as a starting point from which to build code that can be repurposed.

** Note: This is revised based on @WithoutPants feedback and notes on #1831 

### Main Nav Pages
| Site Page      | Title                                     | Example                 | Notes |
| -------------- | ----------------------------------------- | ----------------------- | ----- |
| **MAIN NAV PAGES** |                                           |                         |       |
| Home           | \Stash                 | (Possible down the line to customize) |       |
| Configuration  | \[ConfigPageName\] Configuration \| Stash |                         |       |
| Help           | Help \| Stash                             |                         |       |
| Movies Index   | Movies \| Stash                           |                         |       |
| Scenes Index   | Scenes \| Stash                           |                         |

### Scene
| Site Page        | Title                    | Example                                 | Notes                                                                                |
| ---------------- | ------------------------ | --------------------------------------- | ------------------------------------------------------------------------------------ |
| **SCENES**           |                          |                                         |                                                                                      |
| Individual Scene | \[Movie Title\] \| Stash | "1 Night In Paris" \| Stash              |                                                                                      |
| Scenes Tagger    | Scenes Tagger \| Stash   |                                         |                                                                                      |

### Performers
| Site Page          | Title                                 | Example                           | Notes                                                               |
| ------------------ | ------------------------------------- | --------------------------------- | ------------------------------------------------------------------- |
| **PERFORMERS**         |                                       |                                   |                                                                     |
| Performer Page     | \[Performername\] (Number Of Scenes) \| Stash            | Abella Danger (22 Scenes) \| Stash            |                                                                     |
| Performer Subpages | \[Performername\] Details \| Stash    | Abella Danger Details \| Stash    |                                                                     |
|                    | \[Performername\] Scenes \| Stash     | Abella Danger Scenes \| Stash     |                                                                     |
|                    | \[Performername\] Galleries \| Stash  | Abella Danger Galleries \| Stash  |                                                                     |
|                    | \[Performername\] Images \| Stash     | Abella Danger Images \| Stash     |                                                                     |
|                    | Editing \[Performername\] \| Stash    | Edit Abella Danger \| Stash       |  |
|                    | \[Performername\] Operations \| Stash | Abella Danger Operations \| Stash |

### Studios
| Site Page       | Title                                 | Example | Notes |
| --------------- | ------------------------------------- | ------- | ----- |
| STUDIOS         |                                       |         |       |
| Studio          | \[Studioname\] (part of "parentstudio") \| Stash               | Mofos B-Sides (Part of Mofos Network) \| Stash        |       |
| Studio Subpages | \[Studioname\] Scenes Index (Number Of Total Scenes) \| Stash        | GirlsWay Scene Index (22 Scenes) \| Stash        |       |
|                 | \[Studioname\] Galleries \| Stash     |         |       |
|                 | \[Studioname\] Images \| Stash        |         |       |
|                 | \[Studioname\] Child Studios \| Stash |         |

### Tags
| Site Page    | Title                                        | Example                                   | Notes |
| ------------ | -------------------------------------------- | ----------------------------------------- | ----- |
| TAGS         |                                              |                                           |       |
| Tag Subpages | Scenes Tagged \[Tag\] \| Stash               | Scenes Tagged Anal \| Stash               |       |
|              | Galleries Tagged \[Tag\] \| Stash            | Galleries Tagged Anal \| Stash            |       |
|              | Images Tagged \[Tag\] \| Stash               | Images Tagged Anal \| Stash               |       |
|              | Performers in scenes tagged \[Tag\] \| Stash | Performers in scenes tagged Anal \| Stash |

## Notes
- For any pages with edit functionality, Title should be changed to prepend "\* " when unsaved changes exist

**Comment by gitgiggety** [comment] 2021-07-08 04:52
I might be missing something, but seems like this is a duplicate of #1043 ? Which also discusses what `<title>` to use.

**Comment by jeremymeyers** [comment] 2021-07-08 06:33
blerg. not missing, just a reformatting. will merge tomorrow

**Comment by jeremymeyers** [comment] 2021-07-08 16:27
(closed #1043 instead)

**Comment by WithoutPants** [comment] 2022-03-08 00:28
Closed as complete.

**Closed by WithoutPants** 2022-03-08 00:28 UTC
Labels: help wanted, improvement, chore, ui
