### ISSUE TITLE
[Bug Report] ReadMapCB Error / Host Header error

### ISSUE THREAD

**Issue by stumpylog** [stashapp/stash#1023] opened 2020-12-28 22:45 UTC
**Describe the bug**
When attempting to scrap using a scraper that requires CDP, a brief error message appears in a toast, then vanishes.  It is presumably something about the CDP driver, but the error provides no real help in determining the issue.

**To Reproduce**
1. Go to a scene that uses a CDP community scraper
2. Put in a URL
3. Click Scrape

**Expected behavior**
The scene's data is either scraped, or an error is shown in the logs with enough information to diagnose the issue (rather than a vanishing toast).

**Screenshots**
```log
ReadMapCB: expect { or n, but found H, error found in #1 byte of ...|Host header|..., bigger context ...|Host header is specified and is not an IP address o|...
```

**Stash Version: (from Settings -> About):**

Version: v0.4.0
Build hash: f0ec37c

**Other Information:**

Running Stash via `docker-compose`, with the `chromedp/headless-shell` image providing CDP support.

chromedp/headless-shell version (from http://localhost:9222/json/version):
```json
{
   "Browser": "Chrome/87.0.4280.88",
   "Protocol-Version": "1.3",
   "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
   "V8-Version": "8.7.220.29",
   "WebKit-Version": "537.36 (@89e2380a3e36c3464b5dd1302349b1382549290d)",
   "webSocketDebuggerUrl": "ws://localhost:9222/devtools/browser/21cce012-5eea-4c48-a627-5fa8a54f2568"
}
```

Stash CDP path: `http://headless-shell:9222/json` (also tried with `http://headless-shell:9222/json/version`).  Both containers are on the same network.
User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:79.0) Gecko/20100101 Firefox/79.0`

**Comment by hyde231** [comment] 2021-01-10 19:57
can confirm the error with the exact same setup (dockerized CDP)

**Comment by hyde231** [comment] 2021-01-11 18:39
As requested some details on my dockerized setup:

docker-compose for stash and cdp:

```yaml
version: '2'

services:
  stash:
    image: stashapp/stash:development-x86_64
    container_name: stash
    restart: unless-stopped
    ports:
      - "9999:9999"
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "2M"
    environment:
      - STASH_STASH=/data/
      - STASH_GENERATED=/generated/
      - STASH_METADATA=/metadata/
      - STASH_CACHE=/cache/
    links:
      - chromedp
    volumes:
      - /etc/localtime:/etc/localtime:ro
      ## Keep configs here.
      - /mnt/data/stash/config:/root/.stash
      ## Point this at your collection.
      - /mnt/disks/hdd10/stash/data:/data
      ## This is where pre-generated transcodes live.
      - /mnt/disks/hdd10/stash/transcodes:/transcodes
      - /mnt/disks/hdd10/stash/metadata:/metadata
      ## Any other cache content.
      - /mnt/disks/hdd10/stash/cache:/cache
      - /mnt/disks/hdd10/stash/generated:/generated
    labels:
      - traefik.enable=true
      - traefik.backend=xstash
      - traefik.docker.network=traefik_proxy
      - traefik.frontend.rule=Host:xstash.${tld}
      - traefik.port=9999
    networks:
      - traefik_proxy
      - default
      
  chromedp:
    image: chromedp/headless-shell
    container_name: chromedp
    shm_size: 2gb
    restart: unless-stopped
    ports:
      - "9222:9222"
    networks:
      - default

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge
```

Managed by portainer and connected to Traefik 1.7 as reverse proxy that handles letsencrypt certificates.

CDP version is 
```
{
   "Browser": "Chrome/87.0.4280.141",
   "Protocol-Version": "1.3",
   "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36",
   "V8-Version": "8.7.220.31",
   "WebKit-Version": "537.36 (@9f05d1d9ee7483a73e9fe91ddcb8274ebcec9d7f)",
   "webSocketDebuggerUrl": "ws://192.168.178.24:9222/devtools/browser/24efeec1-970e-404e-b8b2-420f6279010a"
}
 ```
and stash version is
```
Version: | v0.4.0-36-g03a9d65
Build hash: | 03a9d65
Build time: | 2021-01-07 05:14:35
```
Tested in Firefox 84.0.1 (64-Bit) on Win10

The error described appears when trying to scrape a scene with the lates javlibrary scraper. Logs on stash server show absolutely nothing appart from the usual GET and POST requests. Logs in stash only shows this:
```
21-01-11 19:00:29Debug   After: MUM-101
2021-01-11 18:00:29Debug   Before: MUM-101.147cm.A.Previous.Marriage.Of.Daughter-in-law.Shuna.Kagami.mkv
2021-01-11 18:00:29Debug   After: MUM-101.147cm.A.Previous.Marriage.Of.Daughter-in-law.Shuna.Kagami.mkv
2021-01-11 18:00:29Debug   Replace: '(.*[^a-zA-Z0-9])*([a-zA-Z-]+\d+)(.+)' with '$2'
2021-01-11 18:00:29Debug   Before: MUM-101.147cm.A.Previous.Marriage.Of.Daughter-in-law.Shuna.Kagami.mkv
2021-01-11 18:00:29Debug   Replace: '-JG5|-JG6' with ''
```
which is surprisingly little info.

Firefox console shows
```
ReadMapCB: expect { or n, but found H, error found in #1 byte of ...|Host header|..., bigger context ...|Host header is specified and is not an IP address o|... Toast.tsx:54:14
    error Toast.tsx:54
    e SceneEditPanel.tsx:314
    l runtime.js:63
    _invoke runtime.js:293
    E runtime.js:118
    Babel 6
    qe SceneEditPanel.tsx:43
    onClick SceneEditPanel.tsx:43
    onClick SceneEditPanel.tsx:381
    C DropdownItem.js:41
    a useEventCallback.js:6
    h SafeAnchor.js:39
    React 15
        Ue
        Ye
        Or
        Or
        Mr
        Lr
        je
        Lr
        Lr
        Jt
        $t
        unstable_runWithPriority
        Ui
        Ie
        Qt
```

**Comment by bnkai** [comment] 2021-01-11 19:05
@hyde231 can you post more of the log?
when stash starts to scrape using a CDP remote instance it should print something like `Remote cdp instance found ....`
also which setting did you use in the stash UI ? 
`http://localhost:9222/json/version`  or  
`http://192.168.178.24:9222/json/version` ?

**Comment by hyde231** [comment] 2021-01-11 20:53
I used this one in stash: `http://chromedp:9222/json/version` which should work due to the link parameter in the compose file
Without CDP container I get an error message like this when scraping: 
`Get http://chromedp:9222/json/version: dial tcp: lookup chromedp on 127.0.0.11:53: no such host`, so when I don't get this error message, I guess stash finds the remote instance.
With config of `http://localhost:9222/json/version` , I get the error Get `http://localhost:9222/json/version: dial tcp 127.0.0.1:9222: connect: connection refused`
With config of `http://192.168.178.249222/json/version` , I get the no host error again

But no, nothing like remote connection in the logs, no matter what config I used, no matter the log level.

**Comment by hyde231** [comment] 2021-01-11 21:05
Ah screw me, I had a typo in the config above. Now with the correct setting in the UI: `http://192.168.178.24:9222/json/version` it does work. Which surprises me, as I thought I understood docker networking a little...

**Comment by stumpylog** [comment] 2021-01-11 21:30
I fixed this with the network_mode in my compose file.  The CDP is access using `localhost` in this way..  Compose file:

```
version: '3.4'
networks:
  stash-net:
    name: stash-net
services:
  stash:
    image: stashapp/stash:latest
    container_name: stash
    restart: unless-stopped
    ports:
      - "9999:9999"
    networks:
      - stash-net
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "2m"
    environment:
      - STASH_STASH=/data/
      - STASH_GENERATED=/generated/
      - STASH_METADATA=/metadata/
      - STASH_CACHE=/cache/
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./.stash:/root/.stash
      - ./:/data
      - ./.stash/metadata:/metadata
      - ./.stash/cache:/cache
      - ./.stash/generated:/generated
  headless-shell:
    image: chromedp/headless-shell:latest
    container_name: headless-shell
    restart: unless-stopped
    network_mode: "service:stash"
```

**Comment by WithoutPants** [comment] 2021-02-02 00:05
This looks like its resolved. Closing.

**Comment by devster31** [comment] 2021-12-27 20:37
@WithoutPants @bnkai
I encountered the same issue, but I can't host both containers on the same machine.
The problem seems to come from this change [952522: DevTools: check Host header for being IP or localhost when connecting over RDP](https://chromium-review.googlesource.com/c/chromium/src/+/952522) which fixed the following: [Issue 813540: Security: remote debugging + DNS rebinding = UXSS](https://bugs.chromium.org/p/chromium/issues/detail?id=813540).
From what I understand, this means that the `Host` header now only accepts IP addresses or `localhost`.
I believe that a more flexible solution, rather than forcing the containers to share the network, could be to resolve the URL and use the IP before sending the request.
This could be added somewhere around here: https://github.com/stashapp/stash/blob/97b6f5f5c7855979fe6a696f7cfb33df5dff5099/pkg/scraper/url.go#L25

**Comment by bnkai** [comment] 2021-12-27 22:46
> @WithoutPants @bnkai I encountered the same issue, but I can't host both containers on the same machine. The problem seems to come from this change [952522: DevTools: check Host header for being IP or localhost when connecting over RDP](https://chromium-review.googlesource.com/c/chromium/src/+/952522) which fixed the following: [Issue 813540: Security: remote debugging + DNS rebinding = UXSS](https://bugs.chromium.org/p/chromium/issues/detail?id=813540). From what I understand, this means that the `Host` header now only accepts IP addresses or `localhost`. I believe that a more flexible solution, rather than forcing the containers to share the network, could be to resolve the URL and use the IP before sending the request. This could be added somewhere around here:
> 
> https://github.com/stashapp/stash/blob/97b6f5f5c7855979fe6a696f7cfb33df5dff5099/pkg/scraper/url.go#L25

From what i understand from what you link the issue is indeed that we can only use IPs or localhost. If that is the case then we should only need to resolve the address if needed somewhere here 
<https://github.com/stashapp/stash/blob/97b6f5f5c7855979fe6a696f7cfb33df5dff5099/pkg/scraper/url.go#L201>

**Closed** 2022-01-04 04:47 UTC
Labels: help wanted
