### ISSUE TITLE
[Feature] Chromecast support

### ISSUE THREAD

**Issue by Uyloir** [stashapp/stash#766] opened 2020-08-27 17:08 UTC
As the title says; the ability to play videos from Stash to Chromecast would be nice!

**Comment by InfiniteTF** [comment] 2020-08-27 17:40
Duplicate of #363.

@uyloir Casting is already enabled, but you need to enable https for it to work. Please refer to https://github.com/stashapp/stash#ssl-https

**Closed** 2020-08-27 17:39 UTC
