### ISSUE TITLE
Scanning images fails because of image exclusion, despite no image exclusion filter set

### ISSUE THREAD

**Issue by Qlupic** [stashapp/stash#5502] opened 2024-11-22 09:44 UTC
**Describe the bug**
Cannot import pictures to Stash.

**To Reproduce**
1. Make a folder in `/data/test_images/Pack 01`.
2. Add some 12 JPEG pictures to the folder.
3. Go to Stash ➜ Settings ➜ Library. Click on Add Directory and add the folder `/data/test_images`
4. Turn off Videos for the directory, but enable Images.
5. Make sure the "Excluded Image/Gallery Patterns" is empty by clicking on Edit and make sure the field is empty.
6. Go to  Stash ➜ Settings ➜ Tasks ➜ Selective scan. Add `/data/test_images` and click Confirm.
7. Check the Debug log for errors.
8. Notice the error `2024-11-22 10:34:54 Debug Skipping /data/test_images/Pack 01/0001.jpg as it matches image exclusion patterns` and the following errors.

**Expected behavior**
Stash should import the pictures as normal.

**Screenshots**
![image](https://github.com/user-attachments/assets/59733f71-64e3-4355-95e1-b5c62b277e1d)

![image](https://github.com/user-attachments/assets/8cb15add-4065-4568-890e-0be9864c0570)

![image](https://github.com/user-attachments/assets/6926375b-d9a2-4e95-bfc0-6bdda8cd2d7b)

**Stash Version: (from Settings -> About):**

**Desktop (please complete the following information):**
 - OS: Unraid 6.12.10
 - Browser Thorium 128.0.6613.189 (Official Build) (64-bit)
 - Version Stash 0.27.2

**Comment by DogmaDragon** [comment] 2024-11-22 21:11
The issue here is that library directories are traversed recursively. So in your example `/data` will exclude all images, in all subdirectories. 

Duplicate of https://github.com/stashapp/stash/issues/4956

**Comment by DogmaDragon** [comment] 2024-11-22 21:11
Duplicate of https://github.com/stashapp/stash/issues/4956

**Closed by DogmaDragon** 2024-11-22 21:11 UTC
Labels: bug report
