### ISSUE TITLE
[Feature] Performers are limited to a single URL

### ISSUE THREAD

**Issue by miltuss** [stashapp/stash#4791] opened 2024-04-28 09:43 UTC
Hello, I noticed that it is possible to add multiple URLs for scenes

![image](https://github.com/stashapp/stash/assets/152040152/d524f508-b5c4-4770-97ad-53ab6d1af9a4)

But only one URL is allowed for performers!

![image](https://github.com/stashapp/stash/assets/152040152/a1454bcc-927a-4e53-8251-a5012a2bb7b2)

This is illogical because it is mainly the performers who need multiple URLs, not the scenes. In addition stashdb has several URLs for performers but they cannot be integrated into stash!

![Sélection_088](https://github.com/stashapp/stash/assets/152040152/82cc12c2-f7ff-4afd-9552-c2b919080199)

URL integration for performers is a necessity for a good collection

**Comment by Maista6969** [comment] 2024-04-28 09:46
Duplicate of #703

**Closed** 2024-04-28 17:55 UTC
Labels: feature request, duplicate
