### ISSUE TITLE
[Feature] Auto-tag for dates

### ISSUE THREAD

**Issue by kermieisinthehouse** [stashapp/stash#1690] opened 2021-08-30 22:49 UTC
There should be a feature / task that automatically scans your paths (both scenes + images) for dates and assigns them. Many filenames have dates in a few formats, YYYY[.-]MM[.-]DD, MMYYYY or simply YYYY.  Folders may also organize content by release year, such as `Studio/2015/` or `Model/2019/`.

The existing scene filename parser is fairly limited for this usecase must be manually iterated through. A regex that picks up dates and validates them (Perhaps as valid date after 1960) would be great and could possibly reuse some of the regex infrastructure of the autotagger. For partial dates, such as only year or year+month, we can just assign the 01-01.

Considering the model card's "XX Age during this scene", this feature would be useful in populating those throughout a collection.

Some examples / testcases I've tracked down from public scene releases:
```
./Heather/Site - Heather 2009-04-17.wmv
./Micah Moore/micah [IKTG] Oct 28, 2009.mp4
./Julie Silver/flesh for sale (2009) sc1.avi
./Manyvids/vids/20200916-119273743-New_Video_Time..mp4
./Emily 18/2009-03-28 (28).wmv
./Julie Night/ultimatesurrender.com_ ROYAL_MADNESS (2009-08-01_6052).wmv
./Kennedy Kressler/Kennedy Kressler - ALSScan - 7-14-2009.avi
./Kacey Jordan/tlib.20090901_1079_kacey_kara.wmv
./Jessie Rogers/Jessie Rogers Art-Lingerie.com 22.11.2011.wmv
./Olivia Parrish/Olivia - 1995 - Sensual Spirits - Sc5 - 60fps 720p x265.mkv
./Femjoy/Previews 2006-2020/Ariel, Simona - 2010-12-19 - My Love.flv
./Pure18/2010/[Pure18] Parker Page (Phone sex) [14.08.2010][576p].mp4
```

**Comment by echo6ix** [comment] 2021-09-06 03:46
Might be a dupe of or at least related to #484

**Comment by kenetik** [comment] 2021-09-08 12:10
Definitely appears to be a dupe of #484

**Closed** 2021-09-09 08:40 UTC
Labels: duplicate
