### ISSUE TITLE
[Bug Report] "index out of range" Error when Cleaning Entire Library

### ISSUE THREAD

**Issue by FatherManlet** [stashapp/stash#2959] opened 2022-09-28 21:38 UTC
Description:
When trying to run the "Clean" action on the entire Stash library the clean process scans through the directory as normal and marks missing files to clean, when around 40 - 50% through the scan an "Index out of range" error will show and the scan stops. I have included screenshots of the error message and the Stash library stats page in case that relevent to the issue.

1. Go to 'Tasks'
2. Click on 'Clean'
3. Wait around 20 minutes
4. Go to 'Logs'
5. See error

Expected behavior: 
When cleaning the entire library I expect it to go through the entire clean process as normal, instead after around 20 minutes of cleaning the process will stop and the error will be displayed in the logs. This does not happen when doing a selective clean on a subfolder inside the main library folder.

Stash Version: 0.16.1-68-gdce90a3e
OS: Windows 11
Browser: Brave
Version: 1.45.75 Chromium: 106.0.5249.65 (Official Build) beta (64-bit)

Screenshots: 

![Screenshot 2022-09-28 221501](https://user-images.githubusercontent.com/94328082/192892305-863104db-c518-471d-acdd-9ec2886d3888.png)

![image](https://user-images.githubusercontent.com/94328082/192892599-a8f09c1e-2f9e-44a9-8aae-5e3c11cb8fb1.png)

**Comment by WithoutPants** [comment] 2022-09-30 05:35
This is occurring in the internal go zip handling code and will be difficult for me to reproduce. Are you able to narrow down the zip file that is being processed when this occurs? I'd imagine that running a selective scan on the folder containing the problematic zip file should be able to do it, but I don't know how feasible that will be for you.

It's not going to be easy for me to work out the cause independently without the sqlite database, so I'll need work with you to investigate the issue.

**Comment by FatherManlet** [comment] 2022-09-30 18:16
Thanks for looking at this, I am currently waiting for a full scan to finish on my system.  Once this is done I will give the selective scan a try to see if I can narrow down where the issue is coming from.

**Comment by FatherManlet** [comment] 2022-10-10 00:28
Manged to find the zip file that was causing this, I think it was badly packaged as after extracting it and re-zipping it the error had stopped

**Comment by WithoutPants** [comment] 2022-10-11 03:29
Closing this as there doesn't appear much we can do at this point.

**Closed by WithoutPants** 2022-10-11 03:29 UTC
Labels: bug report
