### ISSUE TITLE
Multiple images on one performer 

### ISSUE THREAD

**Issue by ZwiebelTVDE** [stashapp/stash#4732] opened 2024-03-28 15:31 UTC
**Is your feature request related to a problem? Please describe.**
Stash box supports multiple images for one performer but I have to choose one to be shown in my Stash.

**Describe the solution you'd like**
Download all available pictures from stash box and let the user choose what picture gets displayed in overview.

**Describe alternatives you've considered**
I also considered that stash box could have tags for the images the user uploads. In that case a user could specify a Tag in the identity job. Example for image Tags: Frontal nude, SFW, profile picture on Twitter...

**Additional context**
I know that I can go through the performers in the tagger view and choose the picture I want there but this could be a great customization to the way performer are displayed in stash.

**Comment by 7dJx1qP** [comment] 2024-03-28 16:19
There's already an existing feature request for this https://github.com/stashapp/stash/issues/571 and it's on the roadmap.

**Comment by DogmaDragon** [comment] 2024-03-28 18:01
Duplicate of https://github.com/stashapp/stash/issues/571.

**Closed by DogmaDragon** 2024-03-28 18:01 UTC
Labels: feature request
