### ISSUE TITLE
[Feature] Limit tags to scenes or performers

### ISSUE THREAD

**Issue by Spedwards** [stashapp/stash#3327] opened 2023-01-02 07:53 UTC
**Is your feature request related to a problem? Please describe.**
Currently tags are able to be added to both performers and scenes with no separation at all. That means a tag such as "Tattooed" is able to be added to both. A tag like that is what I'd consider to be a performer tag and not a scene tag. This tag should be exclusively used on performers only. Other examples of performer tags could include things relating to piercings, hair colour, the size of certain body parts, etc.
Sure some of these can change over time but that's a problem performer pages already have.

**Describe the solution you'd like**
I'd love to see options on tags that would exclude them from showing up on scenes, whether that's from manual selection, scraping, or using Tagger. The same can be done for performers, for example a "Blowjob" tag makes no sense on a performer.

Below is an example of how the interface would look for tags. By default, both "Allow on Scenes" and "Allow on Performers" would be enabled. I considered having a drop down to select which type of tag it is, but some tags are perfectly valid on both, plus this makes it easier if you were to expand tags to studios (for example an "Anal" tag could be added to studios that always have it, as well as other scenes, but not performers).

![image](https://user-images.githubusercontent.com/3257096/210204978-d884db23-f8f3-499f-9d2b-7b94a974a3fb.png)

**Describe alternatives you've considered**
This is something that has been on my mind for about a year now and in that time, I haven't really thought of any other way to implement this that doesn't add complications down the line if tags were added to studios for example.

Obviously with this approach, when you're filtering scenes by a tag, you would need to include the tags that belong to performers on those scenes. This may already be a feature for all I know, but it's worth mentioning just in case.

**Comment by QxxxGit** [comment] 2023-01-02 17:54
I made a request for this a while back and it's currently in the backlog https://github.com/stashapp/stash/issues/1253

**Comment by stg-annon** [comment] 2023-01-06 22:24
dupe of #1253

**Closed by stg-annon** 2023-01-06 22:24 UTC
Labels: feature request
