### ISSUE TITLE
[Feature] add "watched"-feature

### ISSUE THREAD

**Issue by c-0ne** [stashapp/stash#2975] opened 2022-10-03 22:05 UTC
**Is your feature request related to a problem? Please describe.**
to manage my watched movies i delete them after i watched so i have just "new" movies when i going to watch.

**Describe the solution you'd like**
when i had a feature to filter after "*watched" i can delete them easily. so when a movies is started it should be marked as watched or something similar.

**Describe alternatives you've considered**
no alternatives, its a simple feature

**Comment by 7dJx1qP** [comment] 2022-10-03 22:20
A play counter for scenes is being developed https://github.com/stashapp/stash/issues/633 Not sure if by movies you mean scenes in stash or movies in stash which are collections of scenes.

**Comment by c-0ne** [comment] 2022-10-03 22:38
> A play counter for scenes is being developed https://github.com/stashapp/stash/issues/633 Not sure if by movies you mean scenes in stash or movies in stash which are collections of scenes.

Thats exactly what i need! I meant scenes sorry :)

**Comment by WithoutPants** [comment] 2022-10-05 23:07
Duplicate of #633.

**Closed by WithoutPants** 2022-10-05 23:07 UTC
Labels: feature request, duplicate
