### ISSUE TITLE
[Feature] More Users different access points

### ISSUE THREAD

**Issue by TheZitroX** [stashapp/stash#5404] opened 2024-10-20 07:07 UTC
_Is your feature request related to a problem? Please describe._
Currently, it's not possible to have multiple users with different access levels. This limits flexibility in managing user permissions.

_Describe the solution you'd like_
I want to be able to add more users with configurable access. One user can have the same access as me, while another can have limited access to only their own data. It should be easy to manage and adjust these permissions.

_Describe alternatives you've considered_
Manual workarounds for separating user data, but they are inefficient and difficult to maintain.

_Additional context_
Streamlined user management and access control will improve system efficiency and security (**2FA**).

**Comment by DogmaDragon** [comment] 2024-10-20 14:09
Duplicate of https://github.com/stashapp/stash/issues/2337

**Closed by DogmaDragon** 2024-10-20 14:09 UTC
Labels: feature request
