### ISSUE TITLE
[Bug Report] Stash creating duplicates galleries

### ISSUE THREAD

**Issue by BViking78** [stashapp/stash#1928] opened 2021-10-29 07:55 UTC
**Describe the bug**
Stash sometimes creates a new gallery from the same images while they're already present and even the same gallery is already present.

**To Reproduce**
1. Simply scan/selective scan a folder
2. Another gallery appears

**Expected behavior**
Stash should not create a new gallery from the same images if one is already present.

**Screenshots**
https://imgur.com/a/sFod99U
1. Both galleries showing up
2. New gallery pointing at the same folder but different checksum
3. Original gallery
4. 4&5 1st pic of both galleries, they have the same url since they point at the same folder/image/file

**Stash Version: (from Settings -> About):**
Version: | v0.10.0

**Desktop (please complete the following information):**
 - OS: Win 10&11
 - Browser Firefox/Opera
 - Version 93.0/80.0.4170.63

**Additional context**
The issue is not happening right now and I get the feeling it was (hopefully) only happening to me, I've seen no other reports on Discord. I tried to work it out with Kermie but they couldn't reproduce it so they suggested to open the bug report.

**Comment by Caleripo** [comment] 2021-11-19 14:42
Did you move your files? I have the same problem because I moved all my files to a different drive. When you do a scan the path of the images is automatically updated by stash, but the path for galleries is not. Instead stash creates a duplicate gallery. Stash should update the path of the gallery together with the images instead of creating a duplicate gallery.

**Comment by BViking78** [comment] 2021-11-19 15:02
Nope not at all. If you look at the images those two galleries point to the same images, the only different things is the hash of the gallery, which I have no idea how it's calculated.

Since the opening of this issue, I avoided the problem using selective scan and now switching to zip galleries.
The only thing I can add is:
1) it doesn't happen with zips
2) after all the testing we've done it seesm that it could happen when you have more than 1 instance of Stash running on Win

So the only thing that comes to my mind is what exactly happens if you run two instances of Stash on win that could affect the calculation of the gallery hash so Stash thinks he HAS to create another gallery? Do those two instances share something?
My instances are on different drives and pointing at different locations, in case it helps, so they shouldn't share anything at all!

**Comment by stg-annon** [comment] 2021-11-19 20:11
think thins my be related to #1501 haven't done too much testing since then, essentially been ignoring images and galleries as they take a bit to long on my stash instance compared to scene scans

**Comment by Stephan972** [comment] 2022-04-23 21:33
same on my side. Many galleries get duplicated.

**Comment by BViking78** [comment] 2022-04-24 06:37
> same on my side. Many galleries get duplicated.

My bad I forgot about this bug report I opened.
I dunno your situation but mine is pretty clear by the images and this discussion I had with bnkai on Discord https://discord.com/channels/559159668438728723/559159910550732809/915244408444702750

The real "problem" is that Stash is case sensitive, so when I added the main path it was x:\Porn and then somewhere I renamed the drive to X: hence X:\Porn is different than x:\Porn to Stash (or viceversa it works the same obviously) so at the end a Scan, where Stash reads its configuration X:, behaves differently than a Selective scan, where you feed Stash your "different path" x:.

Check your paths and maybe it's the same issue.

I think the bug can be closed too, since I suppose Stash is case sensitive for a reason!

**Comment by Stephan972** [comment] 2022-05-03 04:50
Here is an example of two duplicate galleries in my stash :

**Gallery #1**
Path: file:///F:/_data/pron/imgs/_archive/2021/04/04/vv/abbywinters/models/nadine
Checksum: aae130299f5d018eb6604e22aae29349
Created At: May 17, 2021 8:39 AM
Updated At: May 3, 2022 6:37 AM

**Gallery #2**
Path: file:///F:/_data/pron/imgs/_archive/2021/04/04/vv/abby-winters/models/nadine
Checksum: f1f5a263b8b21c31fc7fddf261eb31c8
Created At: October 21, 2021 9:36 AM
Updated At: October 21, 2021 9:36 AM

It seems Stash rediscovered the same gallery and decided to add it a second time. Since the checksums are different this may explain why the same gallery is created twice. I don't know what influence this checksum.

**Comment by BViking78** [comment] 2022-05-03 05:44
I've no idea either but you're clearly in my situation:
#1 abbywinters
#2 abby-winters

**Comment by Stephan972** [comment] 2022-05-03 23:39
I tried a selective clean and a selective scan. No tasks removed the gallery #1. Maybe I'll have to manually clean the sqlite database...

**Comment by Stephan972** [comment] 2022-05-03 23:42
> Did you move your files? I have the same problem because I moved all my files to a different drive. When you do a scan the path of the images is automatically updated by stash, but the path for galleries is not. Instead stash creates a duplicate gallery. Stash should update the path of the gallery together with the images instead of creating a duplicate gallery.

In my case I renamed a folder (from "abbywinters" to "abby-winters"). It results a duplicate gallery creation.

**Comment by BViking78** [comment] 2022-05-04 05:49
> I tried a selective clean and a selective scan. No tasks removed the gallery #1. Maybe I'll have to manually clean the sqlite database...

Cleaning won't help in this case, you'll have to manually remove the "wrong/old" gallery, but you can do it in Stash no need to edit the dB manually. The easiest way maybe is to remove both galleries and re-import it once and for all

I've solved this problem converting all my galleries to zips, those are easier to move/rename. In both our cases, mine about being case sensitive, yours about being a different path, Stash will simply update both gallery's path and images' path BUT you'll have to scan twice since they're not updated together, 1st time it'll update zip's path and 2nd time it'll update all images' path!!!

**Comment by AldanaFan** [comment] 2022-06-16 08:28
I have the same issue here. Maybe the checksum for folders is computed wrongly?

There are multiple ways for computing the checksum of a folder, see for instance

https://unix.stackexchange.com/questions/35832/how-do-i-get-the-md5-sum-of-a-directorys-contents-as-one-sum

**Comment by BViking78** [comment] 2022-06-16 15:47
> I have the same issue here. Maybe the checksum for folders is computed wrongly?
> 
> There are multiple ways for computing the checksum of a folder, see for instance
> 
> https://unix.stackexchange.com/questions/35832/how-do-i-get-the-md5-sum-of-a-directorys-contents-as-one-sum

As with Stephan972 I dunno your situation but I would double check everything, 'cause so far it has always been a path "issue" and if the path is different you can't blame checksum calculation, it just does its job

**Comment by AldanaFan** [comment] 2022-06-17 16:14
> > I have the same issue here. Maybe the checksum for folders is computed wrongly?
> > There are multiple ways for computing the checksum of a folder, see for instance
> > https://unix.stackexchange.com/questions/35832/how-do-i-get-the-md5-sum-of-a-directorys-contents-as-one-sum
> 
> As with Stephan972 I dunno your situation but I would double check everything, 'cause so far it has always been a path "issue" and if the path is different you can't blame checksum calculation, it just does its job

I'm not sure if we are talking about the same thing, so I'll try to explain it a little bit better.

Currently I have the following behaviour:
If I change the path of a folder based gallery (like Stephan972) or simply rename it, Stash creates a new gallery (i.e. a duplicate of the gallery pointing to the old path). The metadata (e.g. tags, description, etc.) remains with the old gallery. 

From my point of view I would expect the following behaviour:
If the path of a folder based gallery changes, stash should update the gallery like it does with *.zip galleries.

With the current implementation I have to copy the metadata from the old gallery to the new one, which is really cumbersome. Thus, I changed to *.zip galleries like you suggested previously.

What I observed, is that the checksum of a folder based gallery changes, if you rename the folder, while I do not see this behaviour for a *.zip gallery. So my guess was, that the checksum is computed incorrectly for folder based galleries, since this is more complicated than for a single file. 

Regarding the *.zip galleries, I find it a bit uncomfortable to handle them. I like to still have the option to browse through my galleries within Windows file explorer. 

I know that there are tools, which can handle *.zip galleries (ACD See for instance), but they are still a little bit slow compared to folder based galleries even without using any compression. ACDSee also fails on large galleries (above 3GB). So currently I am using two tools to work with *.zip galleries:  Free Commander and Faststone Maxview. This setup works for me, but I would still prefer the "classic" folder based galleries. But maybe I just did not find the right tools to work with them so far, since *.zip galleries is a new topic for me. So any suggestions/help in this regard is highly welcome.

**Closed** 2022-06-17 17:04 UTC
Labels: bug
