### ISSUE TITLE
[Bug report] Scenes player don't stay in fullscreen

### ISSUE THREAD

**Issue by Sassy0P** [stashapp/stash#3615] opened 2023-03-29 19:31 UTC
Browser: Firefox 111.0.0 (64bit)
Stash:      v0.20.0
___
Hello,
If you play a video in fullscreen and it end, the next video will not be in fullscreen

1. Go to Scenes
2. Select the first one
3. Go Fullscreen
4. Wait for it to finish OR use shortcut P+N
5. Next Video isn't in fullscreen
___
It seems like if the next video as already been started once,  fullscreen mode will stay.

1. Go to Scenes
2. Select the first one
4. Wait for it to finish OR use shortcut P+N
5. Go back(shortcut P+P)
6. Go Fullscreen
7. Wait for it to finish OR use shortcut P+N
8. Then the next Video is in fullscreen

___
Edit:
The console indicate the following warning:
`Exited fullscreen because fullscreen element was removed from document.   index-f68f9f4c.js:106:5592`
___
Edit 2:
Didn't seems to be a problem in v0.19.1

**Comment by DogmaDragon** [comment] 2023-03-29 20:33
Couldn't reproduce on <https://github.com/stashapp/stash/commit/cb8fc3788a3a5268409a7bcd7683904b19a01295>, Vivaldi broser.

**Comment by DingDongSoLong4** [comment] 2023-03-29 23:24
I can reproduce on 2d8b6e1722fb7b5e9aac9c7fbf545cf72cf78f5f in Firefox. What's happening is that while the info for the next scene loads, the loading screen is shown which means that the player element gets removed from the document, as shown in that console line. If the video has already been started, then that scene info is available in a cache so the loading is almost instant and the loading screen does not need to be shown.

Running stash locally probably won't have this issue with a fast PC - the initial scene load will also be fast enough to not need the loading screen.

The fix shouldn't be too complicated, I'll take a look later.

**Comment by DingDongSoLong4** [comment] 2023-03-30 22:27
Alright well the simple fix would have hopefully been React's `startTransition`, but turns out that's only available in React 18 and we're still on 17. Seems like this will have to wait until that migration is done.

**Comment by nothing2obvi** [comment] 2023-04-23 06:47
I have the same issue in Opera Browser.

**Comment by xx790** [comment] 2023-04-23 09:12
Getting this in fresh version of Edge browser.

Check the "Continue" checkbox in the Queue tab, play a video and go fullscreen. It exits from fullscreen when next video starts.

**Comment by StashPowerUser** [comment] 2023-04-26 09:37
just wanted to confirm that I am also experiencing this undesirable behavior.

**Comment by Sassy0P** [comment] 2023-04-27 14:28
I forgot to add that it wasn't a problem in the previous versions I tried

**Comment by nothing2obvi** [comment] 2023-04-27 19:01
@Sassy0P Same here.

**Comment by Dontzi** [comment] 2023-06-14 17:38
Problem is not fixed with v.0.21.0

**Closed** 2023-06-21 23:50 UTC
Labels: bug
