### ISSUE TITLE
[Bug Report] Ordering by title is inconsistent for objects without titles

### ISSUE THREAD

**Issue by echo6ix** [stashapp/stash#3229] opened 2022-12-02 18:07 UTC
**Describe the bug**
Sorting scenes by title is not case agnostic.

**To Reproduce**
Be sure you have scene titles in different cases, such as: `ABC` and `aa`. Create these scene titles if required.

1. Go to `Scenes` (grid view)
2. Click on `Title` and sort ascending
3. The scenes will be sorted with `ABC` first followed by `aa`.

**Expected behavior**
(I think) expected behavior should be `aa` first followed by `ABC`.

**Stash Version: (from Settings -> About):**
v0.18.0-4-g87cea80e

**Comment by echo6ix** [comment] 2022-12-04 23:12
My initial bug report may have been a bit premature in that this may be broken beyond case sensitivity if that at all. It looks like it's definitely taking file path into consideration when sorting. I cannot tell, but all I know is it's definitely not a mere case insensitive sort of all titles.

**Comment by MrX292** [comment] 2022-12-04 23:17
can you filter for `Title is not null` i assume it is only for scenes that have no title

**Comment by echo6ix** [comment] 2022-12-05 00:29
> can you filter for `Title is not null` i assume it is only for scenes that have no title

Ah yes, you're right. That tripped me up. But the initial bug report still stands and can be reproduced. Sorting is not case-insensitive.

**Comment by WithoutPants** [comment] 2022-12-06 04:10
Title is ordered by natural order currently. #1362 is about using case insensitive ordering.

There is however an issue where a mix of objects with and without explicit titles are ordered inconsistently because of the implied title behaviour. I will address this bug, but case insensitive ordering can be considered a duplicate of the existing issue.

**Closed** 2022-12-08 21:29 UTC
Labels: bug report
