### ISSUE TITLE
Custom Fields for Performers

### ISSUE THREAD

**Issue by nathanstreetx** [stashapp/stash#5429] opened 2024-10-30 09:13 UTC
**Is your feature request related to a problem? Please describe.**
No. Just an idea I had.

**Describe the solution you'd like**
I have an interesting idea regarding the performers profile page. Something I like to add to performers profiles is a list of any significant movie's they have been in, a bit like a selected filmography on Wikipedia. Currently I am adding these to the detail text box as shown below.

![image](https://github.com/user-attachments/assets/3dc310e2-7ad8-4e4e-94b5-97db83d22410)

However, I don't actually like how this looks. Now I know that this is a very niche request, and I am not expecting a 'Notable Roles' field to be added, however, I do believe there would be some benefit in being able to create custom fields. Perhaps something after all the other fields (maybe before details) in which you could type in a field title and then then a text box entry for the details. 

Additionally, if this can be made, I would like the ability to add more than one field. Maybe after the first field is entered a new entry option appear, like how URL's work now.

BEHOLD! My very poor render of this solution done in MS Paint
![image](https://github.com/user-attachments/assets/eb30e704-bb98-4259-aaaf-48f7d3f8a39f)
![image](https://github.com/user-attachments/assets/3dcd102f-d3d4-4b28-9360-1e4f985afbb2)
![image](https://github.com/user-attachments/assets/4f718a71-3b86-448d-9bd9-c4a692993130)

**Describe alternatives you've considered**
The alternative would be obviously to make the fields themselves, but like I stated above, no-one wants this 'Notable Roles' field except me and my OCD :)

**Comment by DogmaDragon** [comment] 2024-10-30 11:32
Duplicate of https://github.com/stashapp/stash/issues/885

**Closed by DogmaDragon** 2024-10-30 11:32 UTC
Labels: feature request
