### ISSUE TITLE
[Bug Report] v0.12.0 breaks browsing via Samsung QE55Q6FNAT TV

### ISSUE THREAD

**Issue by bnkai** [stashapp/stash#2273] opened 2022-01-31 17:53 UTC
**Describe the bug**
_Bug reported in discord by user `aviator`_
Upgrading from a previous version of stash (v0.11 was working ok) to 12 makes the browser in the TV show an empty page. Other pcs/laptops in the same network as the tv work fine.  Adding a username/password shows the login page  but after that again a blank page. Switching back to 0.11 makes the tv work again

**Expected behavior**
Stash page showing correctly

**Screenshots**
Empty page from the TV's browser when using latest stash (0.12)
![bug](https://user-images.githubusercontent.com/48220860/151844845-a37a6ebf-1ce1-493f-beb5-1f8cf4eae2a2.jpg)
Http accesss log
![log](https://user-images.githubusercontent.com/48220860/151846618-fec47865-e793-496b-b304-5c99bf5b44b9.png)

Stash is running in a synology as a docker container (using the latest tag)
The issue was encountered after upgrading to latest version
To test we tried switching containers/db back to use the v0.11 version, verified that it worked ok there and then used the `latest` again to verify the issue. While 0.12 was running ok for all other machines in the network it wasnt for just the TV.
No errors seem to appear in stash's log

**Comment by kermieisinthehouse** [comment] 2022-02-05 01:03
Dupe of #2219 

That old chrome blue and the serif-ed 'G' logo tells me this browser hasn't upgraded since 2017 or so. Perhaps we started using a new browser feature that broke old browsers?

**Comment by WithoutPants** [comment] 2024-08-27 04:41
Closing as duplicate of #2219.

**Closed by WithoutPants** 2024-08-27 04:41 UTC
Labels: bug, bug report
