### ISSUE TITLE
[Feature] Change default items per page in galleries

### ISSUE THREAD

**Issue by Written2001** [stashapp/stash#3319] opened 2022-12-30 12:18 UTC
### **Is your feature request related to a problem? Please describe.**
When opening galleries the default value for images per page is 40. Currently there is no way to change the default value to e.g. 120. It's tedious to change the page length every time I open a gallery.

### **Describe the solution you'd like**
I would like to see the option to save the page length (and other filter settings) as default. In other contexts like e.g. the scenes page there is the option to "save filter as default" (including the page length).

### **Describe alternatives you've considered**
I've experimented with Firefox plugins to redirect the gallery page to automatically add the paramenter `?perPage=120` to the end of the URL with the downside of increased loading times. Also there might be a way to solve this with custom CSS or JS snippets.

**Comment by satheeshmsb** [comment] 2023-01-02 03:48
You can select 120 then click the saved filter icon and click set as default.

**Comment by Written2001** [comment] 2023-01-02 14:19
Thank you for your reply.
What you're describing is possible e.g. in the Images tab but not when opening a gallery (At least not for me). 

The image shows what the saved filters menu looks like when looking at a gallery.
![2023-01-02_15-16](https://user-images.githubusercontent.com/121555133/210243419-1f73062a-35d3-4345-ab48-f632821908d0.png)

**Comment by dickscheney** [comment] 2024-01-25 21:40
BUMP!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by dickscheney** [comment] 2024-01-28 00:04
this also applies to scenes/galleries/images on a performer's page, scenes/galleries/images on a tag's page, and scenes/galleries/images on a studio's page

**Comment by kellgrenhbg** [comment] 2024-01-28 09:11
> this also applies to scenes/galleries/images on a performer's page, scenes/galleries/images on a tag's page, and scenes/galleries/images on a studio's page

Yes, this is super irritating. I think there should be global _system setting_ for this. It would probably be good enough to have just one global setting, but it could be different for images/galleries, scenes/movies, and performers. 

It's the performers and galleries that frustrate me. I have a 120 default on performers, but as soon as I choose a performer, I am down to the default of 40. Hopefully, this is not a big feature in implement? Thank you!

**Comment by feederbox826** [comment] 2024-08-19 03:10
duplicate of https://github.com/stashapp/stash/issues/2404
closed by https://github.com/stashapp/stash/pull/4962

**Closed** 2024-08-19 03:12 UTC
Labels: feature request
