### ISSUE TITLE
[Feature] Auto Tag From Details

### ISSUE THREAD

**Issue by meanjoep92** [stashapp/stash#5387] opened 2024-10-16 09:24 UTC
Hey folks, sorry if this has been done before but is there a way to have Auto Tagging based on details of a scene or image? I know it tags based off file path, but just wanted to see if there was another way. Thanks.

**Comment by DogmaDragon** [comment] 2024-10-16 15:12
Sorry, misread the issue initially.

**Comment by DogmaDragon** [comment] 2024-10-16 15:15
Duplicate of https://github.com/stashapp/stash/issues/5387

**Closed by DogmaDragon** 2024-10-16 15:15 UTC
Labels: feature request
