### ISSUE TITLE
[Feature] Allow tags for studios

### ISSUE THREAD

**Issue by jtjb07** [stashapp/stash#4356] opened 2023-12-10 09:13 UTC
**Is your feature request related to a problem? Please describe.**
I have a mix of content in Stash, and I'd like to be able to split studios by broad categories where it makes sense. For example, it'd be nice to be able to view only Japanese AV studios, western content or 3rd party creators of compilations and music videos. This way, if a user is only interested in JAV content, they could have a way to view all available JAV studios. Furthermore, many studios only focus on one specific genre of content (lesbian, POV, interracial, etc) and it might be desirable to filter studios by this.

**Describe the solution you'd like**
Create a tags field for studios. Allow filtering by tags for studios.

Added tags field on studio edit page:
![tags](https://github.com/stashapp/stash/assets/146701633/a1c15fff-cc72-4a41-a45c-bf3a9f69c8ac)
Filtering studios by tags:
![studios](https://github.com/stashapp/stash/assets/146701633/6bbb3b19-4d87-4efa-b4c3-0cfd5e15d48a)

**Comment by echo6ix** [comment] 2023-12-11 04:39
Duplicate of https://github.com/stashapp/stash/issues/2497

**Closed** 2023-12-11 14:32 UTC
Labels: feature request, duplicate
