### ISSUE TITLE
[Feature] Additional shoot date field in scenes and galleries

### ISSUE THREAD

**Issue by peresabcod** [stashapp/stash#3948] opened 2023-07-25 08:59 UTC
**Is your feature request related to a problem? Please describe.**
Sometimes, when a studio re-releases an old set of pictures or a video with higher quality, improved editing, or just it's absorved by another one, having only one field for the date can be confusing:
If a scene shot 10 years ago it's re-released today and you use the release date, the information about the age of the performers in it will be wrong

**Describe the solution you'd like**
Two date fields, (the already existing) one for release and a new one for "shooting" or "original release". The main field would be the current one, and the second one (if not empty) would be used to calculate the performers date in the video or gallery, defaulting to the current behaviour if the new field is empty

**Comment by AdultSun** [comment] 2023-07-25 20:14
Dupe of this issue, also asking for a production date field: https://github.com/stashapp/stash/issues/1078

It's something we're aware of and that I personally have wanted for a long time. It would be particularly useful for tracking and combining multiple releases of the same scene on StashDB as well.

**Closed by AdultSun** 2023-07-25 20:14 UTC
Labels: feature request
