### ISSUE TITLE
In video playback, How to change the default playback stream" direct stream" to "4k hd 1080"

### ISSUE THREAD

**Issue by Aurora-CLW** [stashapp/stash#5447] opened 2024-11-04 03:47 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by feederbox826** [comment] 2024-11-07 20:40
duplicate of #4175

**Closed** 2024-11-08 06:28 UTC
Labels: feature request
