### ISSUE TITLE
Allow the ability to add multiple URLS

### ISSUE THREAD

**Issue by MetalHead2020** [stashapp/stash#3498] opened 2023-03-01 01:58 UTC
The ability to add multiple URLS to a Studio would be nice. In the case where you have content producer that creates content (I.e. studio) but host or sells on different sites such as Clips4Sale or ManyVids. In this case the studio would have multiple URLS to each store. 

Also, it would be nice to be able to add multiple URLS to a performer in addition to the one URL, Twitter and Instagram URLS. Maybe allow multiple URLS to be added with the ability to provide a custom title for each. Like say you could add one for Twitter, Pornhub, IAFD, FreeOnes, etc.

**Comment by Teda1** [comment] 2023-03-01 03:41
This is a duplicate of https://github.com/stashapp/stash/issues/1868

**Closed by Teda1** 2023-03-01 03:41 UTC
Labels: feature request
