### ISSUE TITLE
[Feature] Break movie with only one file into scenes

### ISSUE THREAD

**Issue by alucicrazy** [stashapp/stash#3873] opened 2023-07-01 22:36 UTC
**Is your feature request related to a problem? Please describe.**
I have some movies that have only one file, but i'd like if there was some way to divide them into scenes

**Describe the solution you'd like**
either manually setting the starting point and end point of a scene 

**Describe alternatives you've considered**
 get the slices info from some database

**Additional context**
This is mostly for JAVs

**Comment by echo6ix** [comment] 2023-07-01 23:00
This is a duplicate of #3530 #260 #779

**Closed** 2023-07-04 21:58 UTC
Labels: feature request, duplicate
