### ISSUE TITLE
Performers Page - Non-Binary Performers

### ISSUE THREAD

**Issue by nathanstreetx** [stashapp/stash#5371] opened 2024-10-13 06:35 UTC
Change the Symbol for Non-Binary Performers. Right now it is currently using the Trans Symbol [⚧️] when is should be this [🜬]. I would suggest using purple or yellow as the symbol colour to match their flag

**Comment by feederbox826** [comment] 2024-10-13 08:19
duplicate of #4117

**Closed** 2024-10-13 11:21 UTC
Labels: feature request, duplicate
