### ISSUE TITLE
[Bug Report] Scene covers not generating

### ISSUE THREAD

**Issue by MrPota2** [stashapp/stash#3810] opened 2023-06-10 11:43 UTC
**Describe the bug**
Some scenes have not gotten a cover upon first scan and some covers have been lost. When attempting to generate a new cover nothing happens. 
I have been able to generate for one scene at a time by using the 'generate default thumbnail' button. This is quite tedious however. 

**To Reproduce**
1. Go to 'Scenes'
2. Select scene
3. Click on the 3 dots
4. Click on generate
5. Enable 'scene covers' and 'Overwrite existing generated files'
6. Click on generate

**Expected behavior**
Scene cover is displayed on refresh
censored.

**Stash Version: v0.20.2**

**Server:**
 - OS: Debian Bullseye
 - Docker image: stashapp/stash:latest

**Comment by MrX292** [comment] 2023-06-10 11:51
duplicate of #3657.

**Closed as completed** 2023-06-10 12:07 UTC
Labels: bug report
