### ISSUE TITLE
[Bug Report] Submit to stashbox problems when multiple endpoints exist

### ISSUE THREAD

**Issue by Tweeticoats** [stashapp/stash#3503] opened 2023-03-03 23:03 UTC
**Describe the bug**
When multiple stasbox endpoints are configured updating from one blocks submitting to another.
I have the pmv stash and stashdb endpoints configured.
I would like to pull performer info from stashdb and submit this to pmv stashdb it gets confused and tries to submit an update to stashdb.

There is a stashdb id on the performer, clicking the "submit to stash-box" and selecting the endpoint.
Sometimes this detects that the stashdb endpoint already has a stash id and offers you to update this entry.
Sometimes this wrongly detects that the pmvstash endpoint already has a stashdb and offers you to update this entry.
I suspect the java script seems to not know what endpoint has an id and sometimes thinks that endpoint does not have an id yet.

**To Reproduce**
1.  find a performer
2.  Edit > scrape with > stashdb
3. pull new metadata and save
4. click submit to stash-box
5. select the PMV stash from the list,   the warning "Already exists in pmvstash.org"

It does not happen always and half the time it correctly detects stashdb.org having the stashid and half the time  pmvstash.org has the existing id.

**Expected behavior**
stashdb.org should have the id and offer to update that entry as that has the id but sometimes it thinks pmvstash.org has the id and offers to update that.

**Screenshots**
![image](https://user-images.githubusercontent.com/60335703/222850917-a657c017-0f53-4981-8d8f-887759f5c7c6.png)

**Stash Version: (from Settings -> About):**
v0.19.1-38-ga081b628

**Desktop (please complete the following information):**
 - OS: ubuntu
 - Browser: Firefox
 - Version: 110.0 (64-bit)

**Comment by Flashy78** [comment] 2023-03-04 02:28
The fix for this may be related to the fix for #3483

**Comment by DogmaDragon** [comment] 2023-03-04 10:51
Couldn't reproduce the warning "Already exists in pmvstash.org" on https://github.com/stashapp/stash/commit/e9fa7d071e3587d393cedca735874214e06ff9d9. But found a similar issue. 

- Click `Submit to Stash-Box`
- Select stash-box instance that doesn't have StashID attached
- Click `Close`
- Click `Submit to Stash-Box` again
- Click `Submit`
- See error

Submission failed
`input: Type PerformerDraftInput not found. Check that the config array key for the type matches the name attribute in the type's class. It is required when 'lazyload_types' is enabled`

**Comment by aghoulcoder** [comment] 2023-03-04 11:01
For what it's worth, https://pmvstash.org is running and unmodified `v0.4.6` stash-box.
I haven't looked into the issue beyond this.

**Comment by Tweeticoats** [comment] 2023-03-04 12:12
What seems to have happened is the id's in the local stash have been messed up when updating an existing entry.

To Reproduce

1. Go to the performers tab
2. Select the tagger view
3. click show configuration
4. select pmvstash in the list
5. find an entry with an existing stashdb entry
6. click update

The artist stashid has now been changed to pmvstash

**Closed** 2023-03-19 23:30 UTC
Labels: bug
