### ISSUE TITLE
[Bug Report] Editing tags for multiple selected scenes across several pages only edits selected scenes on currently viewed page

### ISSUE THREAD

**Issue by arkerjames** [stashapp/stash#1598] opened 2021-07-22 12:14 UTC
**Describe the bug**
When viewing the scenes page (e.g. http://localhost:9999/scenes?c={%22type%22:%22duration%22,%22value%22:60,%22modifier%22:%22GREATER_THAN%22}&sortby=random_31833940&sortdir=desc), I can multi-select scenes across several pages and I can switch back to pages with previously selected scenes to verify that the scenes are still selected. But, if I click the Edit icon and add a tag, only the selected scenes on the current page have the tag added to them. 

**To Reproduce**
1. Go to Scenes and make sure you have multiple pages to click through
2. Click on the checkbox on a scene on page 1
3. Go to the second page
4. Clock on the checkbox on a scene on page 2
5. Go back to the first page and confirm that the scene is still selected
6. Go back to the second page and confirm that the scene is still selected
7. Click the Pencil/Edit icon
8. Select Tags > Add and select a tag to add to both those scenes
9. Click Apply
10. Go to the Tags page
11. Select the tag you added
12. Confirm that only the video selected on page 2 has been added to the tag

**Expected behavior**
I would expect all selected scenes to have the tag added. 

**Stash Version: (from Settings -> About):**
Version: | v0.8.0-6-g4bdd759d
Build hash: | 4bdd759d
Build time: | 2021-07-17 09:04:57

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Chrome
 - Version Version 91.0.4472.114 (Official Build) (64-bit)

**Comment by gkddev** [comment] 2021-07-22 12:29
One work around is that you can choose number of videos per page and make sure when you select all files to be on single page before editing it.

**Comment by WithoutPants** [comment] 2021-08-02 00:04
I don't think the way you want this to be is good UX behaviour, and I can't think of any (web)app for which this behaviour is used. Standard practice is that any selections are cleared when changing pages. Otherwise, it becomes more difficult for the user to discern or remember what items have been selected, and with the items not shown on the current page, multi-selection operations (edit/delete) would cause unintended behaviour.

That the item selections are persisting across page changes to me is an unintended side-effect and should probably be removed to eliminate any such expectations that the item selection is persistent across pages.

As noted, the alternative is to use larger page sizes.

I'm going to close this as a Won't Fix unless I can be convinced otherwise.

**Comment by arkerjames** [comment] 2021-08-20 16:27
Happy for this to be a Won't Fix. As you said, expectations were set based on the checkboxes being persistent.

**Closed** 2021-09-09 11:47 UTC
Labels: help wanted, wontfix
