### ISSUE TITLE
[Bug Report] Cannot install: Panic: runtime error: slice bounds

### ISSUE THREAD

**Issue by fellinir** [stashapp/stash#3678] opened 2023-04-22 15:53 UTC
**Describe the bug**
Clicking the exe file, the program cannot install nor open.

**To Reproduce**
1. Execute "stash-win.exe"
4. See error (screenshot below)

**Expected behavior**
The program should install / open

**Screenshots**
![error](https://user-images.githubusercontent.com/92597054/233794009-ce63627f-8e41-4a55-84cd-b7f90d141a6f.png)

**Stash Version**
0.20.2-14-g90683bd2

**Desktop**
 - OS: Windows 10

**Additional context**
Using a WireGuard VPN with firewall

**Comment by MrX292** [comment] 2023-04-23 11:46
i assume you got stash from [here](https://github.com/stashapp/stash/releases) can you try the older releases and see if that makes a difference.

**Comment by fellinir** [comment] 2023-04-23 11:55
> i assume you got stash from [here](https://github.com/stashapp/stash/releases) can you try the older releases and see if that makes a difference.

Yes from there. I tried till 18.0. Same results

**Comment by fellinir** [comment] 2023-04-23 12:20
```
panic: runtime error: slice bounds out of range [:-1] [recovered]
        panic: Panic: runtime error: slice bounds out of range [:-1]

goroutine 1 [running, locked to thread]:
main.handleError({0x1d8fba0?, 0xc0004062a0})
        github.com/stashapp/stash/cmd/stash/main.go:53 +0x93
main.recoverPanic()
        github.com/stashapp/stash/cmd/stash/main.go:44 +0x58
panic({0x1512ac0, 0xc000211398})
        runtime/panic.go:884 +0x212
github.com/spf13/viper.(*Viper).marshalWriter(0xc0002629c0, {0x1da6940, 0xc000207e18}, {0xc000309917, 0x3})
        github.com/spf13/viper@v1.10.1/viper.go:1740 +0xa65
github.com/spf13/viper.(*Viper).writeConfig(0xc0002629c0, {0xc0003098f0, 0x2a}, 0x1)
        github.com/spf13/viper@v1.10.1/viper.go:1619 +0x3ea
github.com/spf13/viper.(*Viper).WriteConfig(0xc0002629c0?)
        github.com/spf13/viper@v1.10.1/viper.go:1557 +0x4a
github.com/stashapp/stash/internal/manager/config.(*Instance).setExistingSystemDefaults(0xc000201740)
        github.com/stashapp/stash/internal/manager/config/config.go:1554 +0x15a
github.com/stashapp/stash/internal/manager/config.Initialize.func1()
        github.com/stashapp/stash/internal/manager/config/init.go:62 +0x17d
sync.(*Once).doSlow(0x30000?, 0x0?)
        sync/once.go:74 +0xc2
sync.(*Once).Do(...)
        sync/once.go:65
github.com/stashapp/stash/internal/manager/config.Initialize()
        github.com/stashapp/stash/internal/manager/config/init.go:41 +0x55
github.com/stashapp/stash/internal/manager.initialize()
        github.com/stashapp/stash/internal/manager/manager.go:164 +0x3d
github.com/stashapp/stash/internal/manager.Initialize.func1()
        github.com/stashapp/stash/internal/manager/manager.go:156 +0x25
sync.(*Once).doSlow(0xf8807?, 0xc00005e000?)
        sync/once.go:74 +0xc2
sync.(*Once).Do(...)
        sync/once.go:65
github.com/stashapp/stash/internal/manager.Initialize()
        github.com/stashapp/stash/internal/manager/manager.go:155 +0x55
main.main()
        github.com/stashapp/stash/cmd/stash/main.go:22 +0x3f
```

**Comment by fellinir** [comment] 2023-04-27 17:47
### Update
Running Windows' troubleshooting compatibility it allowed me to open it (mode: Windows 8):

![image](https://user-images.githubusercontent.com/92597054/234949093-d60195be-e257-4754-ad6f-80d8db005722.png)

**Comment by WithoutPants** [comment] 2023-05-18 00:18
Closing as duplicate of discussion #3679. There's an open question there. This can be reopened if the cause is discovered.

**Closed by WithoutPants** 2023-05-18 00:18 UTC
Labels: bug report
