### ISSUE TITLE
[Feature] Mark Performers/Studios/Groups as organized

### ISSUE THREAD

**Issue by miltuss** [stashapp/stash#5284] opened 2024-09-22 07:59 UTC
I would like to use the brand organized to mark as organized the studios and the performers who are. The organized brand is already present on galleries, images, stages but not on performers, studios, and groups/films!

This mark is very important for the organization of all the elements of the database that I mentioned, not only the elements supported for the moment.

**Comment by feederbox826** [comment] 2024-09-24 16:47
duplicate of #4970

**Closed** 2024-09-24 18:16 UTC
Labels: feature request, duplicate
