### ISSUE TITLE
[Feature] A2HS Support

### ISSUE THREAD

**Issue by shawnshyguy** [stashapp/stash#1303] opened 2021-04-14 21:16 UTC
Hi, I'd like to see [A2HS](https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Add_to_home_screen) support implemented into Stash, for better integration on mobile (though this could also prove beneficial on desktop). The gist of what I'd like to see comes in two parts: An app icon, and an A2HS implementation.
An app icon would be simple enough, just an apple-touch-icon in the header. I say simple, but this would alone improve the presentation on mobile, as here's what Stash currently looks like when added to the home screen:
![image](https://user-images.githubusercontent.com/18062048/114777967-48388c80-9d42-11eb-9b53-e75d470987cf.png)
The more complex part would be the A2HS implementation. This would allow the webpage to act as it's own "standalone" application on mobile and through chrom/ium on desktop. [I'll link an imgur album here](https://imgur.com/a/QANFAEb) with some examples on Stash's current presentation, compared to hydrus.app, another web interface I use regularly from mobile. Screenshots come from Android 10 running Firefox Nightly/Chrome stable, plus a screenshot of Edge on W10, though I'm sure A2HS support works similarly across macOS, iOS, Linux etc.

**Comment by feederbox826** [comment] 2024-08-19 03:30
dupe of https://github.com/stashapp/stash/issues/283 (.webmanifest)

**Comment by DogmaDragon** [comment] 2024-08-19 03:39
Duplicate of https://github.com/stashapp/stash/issues/283

**Closed by DogmaDragon** 2024-08-19 03:39 UTC
Labels: feature, duplicate
