### ISSUE TITLE
[Feature] Add Tag Aliases

### ISSUE THREAD

**Issue by rock4u9** [stashapp/stash#675] opened 2020-07-17 13:13 UTC
Requesting the ability to add aliases to tags which will add the base tag and all aliases during processing.  This will allow scenes and movies to have similar tags associated with it.

For example, the tag MILF would have aliases of Mature, Moms, Cougar.

**Comment by VonTittyslappen** [comment] 2020-07-25 06:38
Would be great to have this for sure, though it would take quite some time to implement at user end when it is in.

I'm part of "theporndb" project (metadataapi.net website) which pierre delecto's script uses. I'm working on tag aliases at the moment, it's a long process, but once it's ready it'll make things much better for those using pierre's script, the tags are a real mess at the moment, thanks to the damn porn sites who use ridiculous tags!

**Comment by echo6ix** [comment] 2020-08-16 18:11
Already suggested I think, a long time ago now. See #121

**Comment by WithoutPants** [comment] 2021-03-24 05:26
Closing as duplicate of #121

**Closed by WithoutPants** 2021-03-24 05:26 UTC
