### ISSUE TITLE
[Feature] Improved Search Functionality

### ISSUE THREAD

**Issue by silembir** [stashapp/stash#1210] opened 2021-03-17 01:17 UTC
Hello,

I think the current search functionality is unintuitive.  For example, when I search "red head kitty", I expect to find the scene titled "red head kitty" as the first result.  Instead, I am presented with every single scene I have that has the words "red", "head", or "kitty" in the title or description.  As someone who has descriptions for almost every scene, this presents a large problem for searching.  I know that I can enter that title in quotes and get the scene I want but there are other examples of this type of search causing an issue.  For example, when I search "skye blue", I typically want just the scenes with Skye Blue, not all the scenes with the word "blue" somewhere in the title or description.  I know that there are workarounds for these issues like searching by performer or even using regex but I am not proficient in regex.  No other porn site has these same search issues.  Apologies if this sounds a bit nitpicky but it greatly affects my regular use of Stash.  I would be happy to provide more examples if needed.  Thanks!

**Comment by bnkai** [comment] 2021-03-17 08:43
posible duplicate of <https://github.com/stashapp/stash/issues/612>
The search as you noticed uses an OR for all terms instead of AND. Apart from the quotes you can use `%` and `_` to refine your search. Eg `red_head_kitty` will return the scene titled `read head kitty` (to be exact `_` matches any single character, not only space) . `sky%blue` will return anything that has `sky` followed by anything else and then `blue` (% matches more than one chars while _ is for a single one)
As for the `no` site uses that, a lot of sites (not sure about apps) use OR instead of AND by default. 
eg [nsfw]
<https://www.brazzers.com/pornstars?q=sky%20blue>
<https://www.21naturals.com/en/search/sky%20blue?query=sky+blue>

**Comment by silembir** [comment] 2021-03-17 12:48
Sure, other porn sites might use OR for search but I'm not sure that those sites are anything to aspire to.  I will use % in the meantime but I'm not sure this is ideal?  It's not very intuitive, especially for new users.  I apologize that I don't have a solution for this problem as I'm not well versed in how programming the search should actually work.

Maybe AND by default would be a better option?  From the other issue you mentioned, it does seem like this is an issue for users or at least not the expected functionality.  Thanks.

**Comment by silembir** [comment] 2021-04-07 20:56
Bumping this issue.  I run into this issue almost every time I use Stash, unfortunately.  Today I searched "One More Time", hoping to find the scene with that exact name.  Instead, I got 1,245 results.  I understand this might be difficult to solve programmatically but it's pretty frustrating.  I'm willing to put a bounty on this feature if necessary.

**Comment by hyde231** [comment] 2021-04-08 19:01
> 
> Bumping this issue. I run into this issue almost every time I use Stash, unfortunately. Today I searched "One More Time", hoping to find the scene with that exact name. Instead, I got 1,245 results. I understand this might be difficult to solve programmatically but it's pretty frustrating. I'm willing to put a bounty on this feature if necessary.

If you wrap the search term into quotes, you will get an exact match. Actually, a single quote at the beginning already triggers this behavior

**Comment by ALonelyJuicebox** [comment] 2021-04-12 05:44
> > Bumping this issue. I run into this issue almost every time I use Stash, unfortunately. Today I searched "One More Time", hoping to find the scene with that exact name. Instead, I got 1,245 results. I understand this might be difficult to solve programmatically but it's pretty frustrating. I'm willing to put a bounty on this feature if necessary.
> 
> If you wrap the search term into quotes, you will get an exact match. Actually, a single quote at the beginning already triggers this behavior

Gotta say...I agree with OP. Putting my search query into quotes really is a workaround, and imo, bad UX..
I'd love to have search queries not default to OR. Even Google implies AND. Maybe a trigger for when you want to OR part of the query?

Ex: A query of `"aaa -OR bbb" ` will return `"aaa.mp4"` and `"bbb.mp4"`

**Comment by m----r** [comment] 2021-06-11 15:43
Can I piggyback on this issue for tag filters?

Example: Suppose I want to see all cat videos that don't include dogs, I'd set two filters at once:

Tags includes cats
Tags excludes dogs

Right now that operation would be treated as an OR. I'd like it to be AND by default.

TIA!

**Comment by GsMumbo** [comment] 2021-06-12 04:03
> As for the no site uses that, a lot of sites (not sure about apps) use OR instead of AND by default.

@bnkai I’m not sure I fully agree here. I think a lot of sites, both NSFW and SFW, use a hybrid. Top results are AND as that is going to be the most accurate. Following that are the OR results as it’s less accurate (one of the conditions isn’t met, but it will hopefully get you close enough to find what you’re looking for). They results are presented as one list to the end user, and usually have the right result in the first few options.

**Comment by jeremymeyers** [comment] 2021-06-13 04:17
prepending a search with "+" seems to imply the following phrase must appear in the results pretty much everywhere, no?

**Comment by bnkai** [comment] 2021-06-13 05:54
> > As for the no site uses that, a lot of sites (not sure about apps) use OR instead of AND by default.
> 
> @bnkai I’m not sure I fully agree here. I think a lot of sites, both NSFW and SFW, use a hybrid. Top results are AND as that is going to be the most accurate. Following that are the OR results as it’s less accurate (one of the conditions isn’t met, but it will hopefully get you close enough to find what you’re looking for). They results are presented as one list to the end user, and usually have the right result in the first few options.


@GsMumbo you are not saying anything different. My main objection was the `NO` site uses OR not that a hybrid or an AND query may be used more than the default OR.

**Comment by WithoutPants** [comment] 2021-09-17 22:11
I agree that searching by query string should AND the terms by default. 

I'd propose a similar syntax to Google and Bing:
- AND terms by default
- OR (or |) operator to or terms together
- use quotes for literal phrase or word (to escape OR for eg)
- NOT (or -) operator to exclude terms

This will bring the search functionality more in line with conventions, while allowing access to the old behaviour.

**Comment by jeremymeyers** [comment] 2021-09-18 01:54
would also add "+" to require a thing in the search results, to do for example

anabolic OR Diabolic +"initiations"

**Comment by WithoutPants** [comment] 2021-09-18 05:02
$40 bounty added.

**Comment by WithoutPants** [comment] 2021-09-19 23:51
$30 bounty added - $70 total bounty.

**Comment by WithoutPants** [comment] 2021-10-31 23:33
$30 bounty added - $100 total bounty.

**Closed** 2021-11-22 03:59 UTC
Labels: improvement, bounty
