### ISSUE TITLE
[Feature] Allow two profile images for performers

### ISSUE THREAD

**Issue by miltuss** [stashapp/stash#5287] opened 2024-09-22 12:34 UTC
Films/Groups in stash are entitled to two cover images, while performers are only entitled to one profile image!

I would like to use a standard profile image for performers and another NSFW image.

This could be done in different ways:

1 - Mouse Rover on the performer card to display the second image
2 - directional arrow on the card to scroll to the second image
3 - Button on the card to switch from one image to another
...

All these methods of displaying the second image can be offered in the settings to the user and let him choose the one he prefers.

**Comment by DogmaDragon** [comment] 2024-09-23 05:06
Duplicate of https://github.com/stashapp/stash/issues/571

**Closed by DogmaDragon** 2024-09-23 05:06 UTC
Labels: feature request
