### ISSUE TITLE
[Bug Report] Auto Tag not tagging images

### ISSUE THREAD

**Issue by koala640** [stashapp/stash#991] opened 2020-12-13 06:19 UTC
**Describe the bug**
When pressing “auto tag” button on the performer page it’ll find all the scenes but no images.

**To Reproduce**
1. Create a folder called PERFORMERNAME
2. In PERFORMERNAME put in some images and some video file
3. Create a performer named PERFORMERNAME
4. On their profile go to Operations, Auto Tag
5. Video files show up in scenes, but no images

**Expected behavior**
Images should be auto tagged too.

**Stash Version: (from Settings -> About):**
v0.4.0-21

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser N/A
 - Version N/A

**Comment by SpedNSFW** [comment] 2020-12-13 07:10
I'm presently unable to reproduce this, so I'll ask a few questions instead:

1. Are image scans excluded on your drive?
2. Are the images present in Stash at all?
3. Was a gallery perhaps created for the images, and if so, was that auto tagged?

**Comment by koala640** [comment] 2020-12-13 08:35
hello. no images scans are not excluded. images are present in stash and in galleries. galleries are not tagged either. PERFORMERNAME is in folder name not in file name btw

**Comment by WithoutPants** [comment] 2020-12-17 03:18
Auto tag is currently not implemented for images or galleries.

**Comment by WithoutPants** [comment] 2020-12-17 03:19
Duplicate of #977

**Closed by WithoutPants** 2020-12-17 03:19 UTC
Labels: duplicate
