### ISSUE TITLE
[Bug Report] Tagger replaces existing StashBox ID instead of adding it

### ISSUE THREAD

**Issue by JackDawson94** [stashapp/stash#4290] opened 2023-11-19 00:19 UTC
**Describe the bug**
When working with multiple StashBox instances (eg: StashDB & PMVStash), performers might be on both platforms.
If I search for a performer using the Edit / Scrape With feature, I can add both StashBox links to the performer.
But if I do it with the Tagger, it doesn't work.
For example, if the performer already has a StashDB link, and I use the Tagger to search for the PMVStash entry. When I click "Save", the PMVStash link is added, but the StashDB link is removed.

**To Reproduce**
1. Go to Performers -> Tagger view
2. Select StashDB in the Tagger config
3. Scrape the performer on StashDB and Save
4. Switch the Tagger to use PMVStash
5. Scrape the performer on PMVStash and Save

**Expected behavior**
Links to all StashBox instances should be savec

**Stash Version: (from Settings -> About):**
0.23.1

**Comment by scruffynerf** [comment] 2023-11-19 00:39
I believe this is fixed in v24

**Comment by DingDongSoLong4** [comment] 2023-11-19 00:42
Yes this is a duplicate of #4212, which was fixed by #4215. That fix will be in v24.

**Closed by DingDongSoLong4** 2023-11-19 00:42 UTC
Labels: bug report
