### ISSUE TITLE
[Feature] The ability to delete cover image on a scene

### ISSUE THREAD

**Issue by rawbeastly** [stashapp/stash#5464] opened 2024-11-08 02:25 UTC
**Is your feature request related to a problem? Please describe.**
I notice I have some false positives on stash-db, and the metadata i had it bring in on some scenes. I was able to delete all the erroneous metadata off of the file in stash, but not the cover image. I can only add a new cover image.

**Describe the solution you'd like**
I'd like to just be able to delete the cover image, and not have to replace it with something else.

**Comment by DogmaDragon** [comment] 2024-11-08 06:27
Duplicate of https://github.com/stashapp/stash/issues/4789

**Closed by DogmaDragon** 2024-11-08 06:27 UTC
Labels: feature request

**Comment by boivinx7** [comment] 2024-11-23 21:22
Would love this too, the SLR provider has put a ton of cover images on a ton of scenes, and not gotta go and do a generate with replace on all in batch, i dont want to do a big generate with replace because it replaces the goods ones too and i cant find a way to delete those by GUI, API or SQLite query
