### ISSUE TITLE
[Bug report] Enable quick toggling of sub-tag/sub-studio content

### ISSUE THREAD

**Issue by itanameiguess** [stashapp/stash#4938] opened 2024-06-06 21:24 UTC
**Is your feature request related to a problem? Please describe.**
When using studio/tag hierarchies there may be many levels of parent tags/studios. Previously it was relatively easy to open the pre-applied filter and toggle inclusion of sub-content, now a new filter must be applied to include content you are looking at then toggled

**Describe the solution you'd like**
Add an option to toggle inclusion of sub-tag/sub-studio content when viewing any tag/studio which is a parent. Default setting is available as an option already but changing views can be desired

**Describe alternatives you've considered**
Returning previous behavior changed by 4705 as plugin/settings toggle

**Additional context**
Behavior changed due to https://github.com/stashapp/stash/pull/4705 with v26.0

**Comment by WithoutPants** [comment] 2024-06-07 03:30
Marking this as a bug because it is a regression of previous behaviour.

**Closed** 2024-07-31 06:35 UTC
Labels: bug report
