### ISSUE TITLE
[Bug Report] Some scenes not showing scene scrubber as it's using checksum filenames instead of hash

### ISSUE THREAD

**Issue by goldstar1x** [stashapp/stash#3580] opened 2023-03-22 06:07 UTC
### Summary
A bunch of my scenes are showing blank scene scrubber images. Not clear how many scenes are affected but I'd say it's a large number. 

### Screenshots
![image](https://user-images.githubusercontent.com/65011124/226815011-2afa88fb-fb11-4644-9c71-d49962413a5e.png)

**Hash and Checksum:**
![image](https://user-images.githubusercontent.com/65011124/226815881-2ea48c93-7817-4737-b03e-de47ed439d32.png)

### Things I've tried & noticed:
- Regenerate function on individual scene, tick scene scrubber and tick Overwrite existing. Does nothing
- When I inspect the page, I noticed the image it's looking for is `53cff17ade9aa5b466c4633e4aadadb1_sprite.jpg`. This filename corresponds to the scene's checksum value. 
- The generated scene scrubber image exists on disk as `63044a542a9c2066_sprite.jpg`, this file name would correspond to the scene's hash. 
- In my stash system settings, I am using oshash Hashing, and have been using it since it became available, I have not switched hashing at any time. 
- It looks like all scenes that do have a checksum have this problem. If I filter for `checksum is not null` I can see they all don't show scene scrubber. 

**Stash Version: (from Settings -> About):**
v0.19.1-79-gf6387c10

**Desktop (please complete the following information):**
 - OS: Windows 10 x64
 - Browser Chrome 111.0.5563.65

**Additional Context**
There's a task that renames the generated files to the correct name, so if I was using md5 before and I switch to oshash, it renames all my md5-named files to oshash-names

But that's not going to work for me, since the generated files are already using the correct oshash name, the problem is the scene itself is looking for the wrong name

**Comment by WithoutPants** [comment] 2023-03-22 23:46
The root cause of this is #2481, which migrated the hashes without modifying the vtt file contents. I have the same issue on my system. Regenerating the sprites with overwrite turned on does fix this issue.

This issue is manifesting now due to the #3513 changes. I can change code to be able to resolve the correct file like the old behaviour, but I don't believe it's correct. I think there are a relatively small number of users impacted by this, and we should solve the problem another way, rather than maintaining what is essentially incorrect behaviour. The (worst) workaround is to regenerate the affected vtt files.

I used the following script to fix my vtt files:
```
#!/bin/sh

if [ $# -lt 1 ]; then 
    echo "Usage: fix-vtts.sh <path to /generated/vtt directory>"
    exit 1
fi

for f in `find "$1" -name "*.vtt"`; do
    hash=`basename "$f" | sed -e 's#_thumbs.vtt##g'`
    grep "$hash" "$f" > /dev/null && continue

    echo "Fixing $f"
    sed -i -e "s#^[^_][^_]*_sprite#${hash}_sprite#g" "$f"
done
```

Closing as I don't believe there will be a code fix for this.

**Closed by WithoutPants** 2023-03-22 23:46 UTC
Labels: bug report
