### ISSUE TITLE
[Feature] Clear metadata

### ISSUE THREAD

**Issue by echo6ix** [stashapp/stash#5276] opened 2024-09-19 22:39 UTC
**Is your feature request related to a problem? Please describe.**
There are only two methods that I know of to bulk clear metadata from one or more top level objects.

1. Edit each object manually, by clearing each field manually. This is extremely laborious.

2. In grid view, selecting one or more items, clicking delete and unchecking the the options to delete files and generated data. Then rescanning the library. This is clearly not an ideal solution.
  a. If a user mistakenly does not uncheck `Delete file` and/or `Generated files`, the consequences range from catastrophic to very time consuming if they have to generate supporting files again
  b. This would also remove the user's playback history, created at, and updated at metadata, which may not be desirable

**Describe the solution you'd like**
Add a `Clear metadata` option to the toolbar overflow menu for all top level objects
- Add a modal confirmation dialog
- Modal confirmation dialog presets the users with a warning, and three checkboxes
   1. `Clear all metadata`. This is the general metadata associated with the content
   2. `Clear playback history`. This clears the playback history of the items
   3. `Clear file metadata`. This clears metadata related to *created at*, and *updated at* timestamps

**Additional context**
![image](https://github.com/user-attachments/assets/d1cbeb0c-f21c-4f06-b4f7-3ad5cfd97d21)

The word "clear" was used instead of "delete" purposely. To unambiguously distinguish between the actions of deleting a file and clearing metadata.

Edit: Modal and overflow item should be labeled `Clear metadata` instead of `Clear all metadata`, since the user can select between the types of metadata to clear in the modal.

**Comment by fangly-fish** [comment] 2024-09-19 22:59
love to see this. Emby/Jellyfin have a _Remove Identification_ option that clears out all the metadata that a metadata scraper can add.

![image](https://github.com/user-attachments/assets/f4262744-1002-4f85-9d60-819308539b31)

**Comment by feederbox826** [comment] 2024-09-19 23:36
dupe of https://github.com/stashapp/stash/issues/3878

**Comment by echo6ix** [comment] 2024-09-19 23:38
😅 I forgot about that, and even commented on it.

**Closed** 2024-09-19 23:38 UTC
Labels: feature request
