### ISSUE TITLE
Windows Explorer links

### ISSUE THREAD

**Issue by bogbrush1** [stashapp/stash#5342] opened 2024-10-04 16:59 UTC
In file info it would be great to have clickable Windows Explorer links that opens the file location in Windows for a scene

At the moment the format for example _file://E:A\PERFORMER NAME\%20 FILENAME %20_ isn't recognised in Windows Explorer (I think spaces in filenames are being replaced by %20 etc)

Would be very useful in order to tidy up files/delete dupes etc to have this function. You are going to tell me it already exists somehow but I haven't found it yet!

**Comment by DogmaDragon** [comment] 2024-10-04 17:58
Duplicate of https://github.com/stashapp/stash/issues/1485

**Closed by DogmaDragon** 2024-10-04 17:58 UTC
Labels: feature request

**Comment by bogbrush1** [comment] 2024-10-05 01:37
Hi - no issues with you closing my thread but:

I did read #1485 <https://github.com/stashapp/stash/issues/1485> before
posting, and as other posters make clear the suggested Firefox add-on to
deal with my feature request doesn't function correctly and has not been
updated recently

I couldn't post in thread 1485 as it is closed, so my feature request is
still potentially valid?

**Comment by DogmaDragon** [comment] 2024-10-05 01:43
@bogbrush1 the issue is open.
![image](https://github.com/user-attachments/assets/70695bd1-1fd9-4ce8-b050-eda7cdad4f64)

Though, it has low chance of getting implemented into Stash due to browser sandboxing. It's better/faster to be solved via plugin or external tool.
