### ISSUE TITLE
I hope to add the function of setting a certain picture as a cover in the gallery.

### ISSUE THREAD

**Issue by jack3014** [stashapp/stash#4907] opened 2024-06-03 01:32 UTC
I hope to add the function of setting a certain picture as a cover in the gallery. It is best to set it with one click, or support custom shortcut keys

**Comment by DogmaDragon** [comment] 2024-06-03 08:41
Duplicate of https://github.com/stashapp/stash/issues/1432

**Closed by DogmaDragon** 2024-06-03 08:41 UTC
Labels: feature request
