### ISSUE TITLE
[Bug Report] When Not Using a Browser, HTTPS GraphQL links do not have correct Scheme

### ISSUE THREAD

**Issue by devloch** [stashapp/stash#2764] opened 2022-07-21 18:18 UTC
**Describe the bug**
When starting up Stash using a server cert and key, and performing graphQL calls not using a standard login/browser flow, the generated links for things like screenshots, etc have an http prefix rather than https.

This happens regardless of whether using a session cookie, or an API key.

**To Reproduce**
1. Run stash in HTTPS 
2. Open network debugger in Chrome HTTP browser (or your choice, steps are for Chrome)
3. Navigate to "scenes"
4. Find a graphql query that has a network response that includes data like "paths":{"screenshot":"https://stashapp.docker:5070/scene/305/screenshot?1658361816"
5. Right click the query and select "copy as powershell"
6. Run the query in powershell and display the resulting body of the message (e.g. prefix Invoke-WebRequest with "$response = " and then do "Write-Output $response.Content"
7. The resulting data has return values prefixed with "http" rather than "https"
8. You can also repeat the above steps except with an API key (remove the Cookie and add an ApiKey header)

**Expected behavior**
When running stash over HTTPS, the generated/returned links should be HTTPS, as HTTP will not work.

**Stash Version: (from Settings -> About):**
v0.16.0

**Additional context**
If I had to guess, it's probably something in the server.go BaseURLMiddleware function not working correctly for all inbound requests. The documentation for request.Proto implies that it expects the value to be HTTP/2 rather than HTTP/2.0, so perhaps the standards changed enough that protocol isn't being picked up?
https://cs.opensource.google/go/go/+/refs/tags/go1.18.4:src/net/http/request.go;l=129

**Comment by WithoutPants** [comment] 2022-09-08 06:25
I tried to reproduce using Linux and `curl`, but the paths are coming back with the correct `https` scheme.

**Comment by WithoutPants** [comment] 2022-09-08 06:53
I've been able to get the request to execute via powershell. I'm not sure exactly what's going on, but it looks like the TLS protocol isn't being validated correctly when done via powershell.

Delving into the golang `http` server code. It checks the `NegotiatedProtocol` field for a valid ALPN protocol name. In the connection from powershell, this field is resolving to an empty string. When this occurs, it falls back to http/1.1. The weird thing is, is that the powershell command returns successfully on the https connection despite not passing in the required certificate for validation. I'd expect it to fail because of this. I wasn't able to get it to fail due to an invalid certificate. 

In constrast, curl failed if I didn't provide the certificate. If I did provide the certificate, then it returned as normal with the correct paths.

**Comment by devloch** [comment] 2022-09-08 18:43
Huh, guess that's my mistake for only testing with Powershell and just assuming it would work the same in curl.

I will note I first ran into this when I was updating the stash-vr-companion to support HTTPS - the Python requests (from URL library) that it was making to stash were getting the same behavior, where returned URLS had HTTP rather than HTTPS. In that case, it was performing certificate validation and throwing an error otherwise (part of my updates were to allow for removing the validation flow, so I'm 100% confident it was performing and then failing on cert validation).

**Comment by WithoutPants** [comment] 2022-09-08 23:07
If I don't get to it first, you could try making a simple python script to reproduce.

**Closed** 2022-09-14 04:20 UTC
Labels: bug
