### ISSUE TITLE
[Feature] Additional Performer Database field for Penis Type

### ISSUE THREAD

**Issue by KrisVardo** [stashapp/stash#3267] opened 2022-12-11 18:15 UTC
As [mountainmantra](https://github.com/mountainmantra) pointed out here:
https://github.com/stashapp/stash/discussions/3265#discussion-4649812

"The current implementation of the performer table is gender specific, for females. It seems that the original intention of the Measurements field is for Breast Size, with the following field being Fake Tits."

Screenshot:
https://user-images.githubusercontent.com/11653895/206876677-261cdd54-0d33-40d6-89ab-33938322002b.png

Based on our discussion here:
https://github.com/stashapp/stash/discussions/3265#discussioncomment-4372650

**A new text field should be added, "Penis Type".**  
Penis Type can capture circumcised status, as well as be open-ended for other situations (prosthetic, etc.).

It should be a new field, rather than overload "Fake Tits". There are trans performers with both. Both "Penis Type" and "Fake Tits" should probably be available always (for any gender), and can just be "n/a" if they don't apply.

**Comment by KrisVardo** [comment] 2022-12-11 22:55
Screenshot of how this would look:

<img width="1084" alt="Screen_Shot_2022-12-11_at_2_54_43_PM" src="https://user-images.githubusercontent.com/114971575/206933763-270eab64-ea89-4cb3-afba-8f295817566a.png">

**Comment by strubdog** [comment] 2022-12-11 23:20
I love this idea.

**Comment by echo6ix** [comment] 2022-12-12 09:02
Basically a duplicate of https://github.com/stashapp/stash/issues/2735 (though it might be phrased awkwardly in the latter issue).

- Displaying fields with `N/A` isn't necessary, it just adds visual clutter. It's essentially a null value, and the omission of the field communicates the same meaning (that it is N/A). 
- Penis size and "penis type" should probably be split into different fields at least on the backend to facilitate filtering/queries:
  - `Penis size`: *integer*
  - `Foreskin`: *boolean*
    - `True`: Uncut
    - `False`: Cut
  - `Penis type`: *string*
    - ????????????????????????????

**Comment by binarygeek119** [comment] 2022-12-12 18:32
Should also add thickness

**Comment by KrisVardo** [comment] 2022-12-13 00:54
I don't think you're going to get that much detailed data about that many performers, enough to make it searchable or worth it.  Or that's consistent - especially on size.  I think that's making it too complicated, even though it would be nice/interesting.  Just having a field to store some words that are searchable is enough.  It's easy to search for "contains 'uncut'" in the "penis type" field and find them all.

**Comment by DogmaDragon** [comment] 2022-12-13 05:07
> I don't think you're going to get that much detailed data about that many performers, enough to make it searchable or worth it. Or that's consistent - especially on size. I think that's making it too complicated, even though it would be nice/interesting. Just having a field to store some words that are searchable is enough. It's easy to search for "contains 'uncut'" in the "penis type" field and find them all.

There are plenty of details provided by studios for non-straight performers to fill in the fields.

**Comment by Maista6969** [comment] 2024-02-10 01:57
Looks like this can be closed since #3627 was merged

**Closed** 2024-02-10 11:57 UTC
Labels: feature request
