### ISSUE TITLE
[Feature] Mark scene as Complete Movie

### ISSUE THREAD

**Issue by hurricaneporter** [stashapp/stash#2567] opened 2022-05-06 20:55 UTC
**Is your feature request related to a problem? Please describe.**
Some scene files comprise the entirety of a movie. This can get confusing alongside individual scene clips.

**Describe the solution you'd like**
A picker in the Movie editor, including all associated scenes, that blesses one scene as "complete".

**Describe alternatives you've considered**

- A filter of all organized scenes over 60 minutes long associated with a Movie.
- Marking a scene as Movie scene # 0.

**Comment by WithoutPants** [comment] 2022-05-09 00:22
Duplicate of #779.

The movie object will eventually change to allow a direct association with a file so that this won't be necessary.

**Closed by WithoutPants** 2022-05-09 00:22 UTC
Labels: feature request
