### ISSUE TITLE
[Feature] Sort Scenes by Studio Code?

### ISSUE THREAD

**Issue by NormanPriv** [stashapp/stash#5398] opened 2024-10-19 06:06 UTC
**Is your feature request related to a problem? Please describe.**
There does not seem to be a way to sort the scenes by studio code.

**Describe the solution you'd like**
Sort by studio code lexicographically. Place any scene without a studio code at the end.

Related to this is that, it would nice to optionally display studio code in the "card" as well.

**Additional context**
For some studios, the studio code is ordered in a meaningful way, like a playlist. The content in them are like a series when following the order of the studio code. However, it is not always convenient to use an alternative criterion as a substitute.

**Comment by DogmaDragon** [comment] 2024-10-19 17:57
Duplicate of https://github.com/stashapp/stash/issues/4293

**Closed by DogmaDragon** 2024-10-19 17:57 UTC
Labels: feature request
