### ISSUE TITLE
[Feature] Cover Image by URL

### ISSUE THREAD

**Issue by niemands** [stashapp/stash#830] opened 2020-10-05 12:10 UTC
**Is your feature request related to a problem? Please describe.**
Sometimes thumbnails can't be scraped or a site has a better image in the gallery that I would like to use as cover image.
Usually I have to download the images and add them with the 'Browse for image...' button. I would love to have a way for entering the image url, which will then be downloaded automatically similar to the scraper image function.

**Describe the solution you'd like**
A button which allows the user to insert an url, which will then be downloaded and set as cover image automatically.

**Describe alternatives you've considered**
Maybe Drag and Drop, but then you would still have to download the images manually. Alternatively a way to set an image from the attached gallery as cover, however this would require the scene to have a gallery attached, which is not the case in most of the times.

**Comment by Belleyy** [comment] 2020-10-05 12:35
You can copy the image (Right click on image in your browser) then go in edit scene and paste it (Ctrl+V). It will put the image as Cover image.
So you don't need to download the image.

**Comment by niemands** [comment] 2020-10-05 12:47
@Belleyy This does not work for me (Firefox), also this would save the image in the database and not in the folder.

**Comment by halorrr** [comment] 2020-10-06 05:32
This is a duplicate of https://github.com/stashapp/stash/issues/479

**Closed** 2020-10-06 06:24 UTC
Labels: duplicate
