### ISSUE TITLE
[Bug Report] Save button disabled after changing the tag image

### ISSUE THREAD

**Issue by SirCumAlot1988** [stashapp/stash#3552] opened 2023-03-16 17:04 UTC
**Describe the bug**
If you change the image of an existing tag and do not modify anything else, the save button is disabled. You have to change something else (e.g. the description section) in order to save your changes.

This was working in Stash v0.18.0

**To Reproduce**
1. Go to Tags
2. Click on an arbitrary tag
3. Click on Edit
4. Choose a new Image
5. Save button is disabled
6. Enter some text under "Description"
7. Save button becomes enabled

**Expected behavior**
Save button should be enabled as soon as the tag image changes

**Stash Version: v0.19.1

Desktop (please complete the following information):

    OS: Win 10
    Browser Firefox
    Version 110.0.1

**Comment by DingDongSoLong4** [comment] 2023-03-16 20:59
I think this has been fixed but just not released yet - I can reproduce the issue on v0.19.1 but not on the latest development build.

**Comment by WithoutPants** [comment] 2023-03-16 22:24
Duplicate of #3489

**Closed by WithoutPants** 2023-03-16 22:24 UTC
Labels: bug report, duplicate
