### ISSUE TITLE
[Bug Report] merge tags option in scene tagger is broken

### ISSUE THREAD

**Issue by CuddleBear92** [stashapp/stash#2367] opened 2022-03-06 21:49 UTC
Currently the merge tags option in the scene tagger is broken. It overwrites all your tags even when its set to merge. 
I'm currently running on v0.12.0 in a docker container on my NAS. 

I have tested this multiple times now, adding tags manually to a scene only to use the tagger with the merge option set. 
For it to wipe the tags i manually added.

![image](https://user-images.githubusercontent.com/8496821/156943486-6ca325f0-77b7-482b-9a5d-9252ae9e7f20.png)

Expected behavior with a "merge" option would be that it appends and just add the tags it pulled without removing any of the already in place tags.

**Comment by WithoutPants** [comment] 2022-03-07 05:45
The tag strategy is applied in the GUI and is applied immediately to existing results.

If `Merge` is selected and a scene has existing tags, then these tags are appended to the tags editor in the search result:

![image](https://user-images.githubusercontent.com/53250216/156974742-987d4741-32d8-4bc4-a1dc-7ce067f1bb32.png)

Clicking save, I could verify that the existing tag was maintained.

If `Overwrite` is selected, then the tags editor shows only the new tags.

I'm not able to reproduce this issue. I suspect it's a misunderstanding of behaviour, or possibly that the client had out-of-date data and was not populating the existing tags correctly. Otherwise, please list detailed instructions on how to reproduce.

**Comment by bnkai** [comment] 2022-03-07 09:05
@CuddleBear92  Can you try the dev version or wait a couple of days to try the next stable? We cant reproduce using the dev version.

**Comment by WithoutPants** [comment] 2022-03-24 00:21
Closing as presumably resolved.

**Closed by WithoutPants** 2022-03-24 00:21 UTC
Labels: bug
