### ISSUE TITLE
[Bug Report] Blobs system, saving performer image then immediately updating new image gives delete error

### ISSUE THREAD

**Issue by elkorol** [stashapp/stash#3717] opened 2023-05-03 04:03 UTC
**Describe the bug**
With the new blobs system, when creating or editing a performer, giving the performer an image, upon save then immediately editing the performer and uploading a new image and saving, gives a delete error for the existing blob image.

The error is like
deleting from filesystem: deleting file {Blob Image File Path}: marking file {Blob Image File Path} for deletion: rename {Blob Image File Path} {Blob Image File Path}.delete: The process cannot access the file because it is being used by another process.

**Expected behavior**
For the image to be able to update to the new image and delete the existing image

**Stash Version: (from Settings -> About):**
v0.20.2

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version: 112.0.5615.138 (x64)

**Comment by WithoutPants** [comment] 2023-05-04 06:10
I've been unable to reproduce this so far. The method I used is as follows:

1. copy an image to clipboard
2. edit a performer, paste the image
3. copy a different image to clipboard
4. save the performer
5. immediately edit the performer, paste the image and save

**Comment by elkorol** [comment] 2023-05-05 09:14
It's still happening for me, I'll setup a fresh copy of Stash to see if that solves it. And turn off my AV etc.

**Comment by elkorol** [comment] 2023-05-05 09:47
I tested with a Stale copy of version 19, I had, updated to V20.2. I performed changing Binary data storage type to filesystem and set blob path. Performed the migrations. I made a new performer, updated with an image and immediately after saving I clicked edit and copied an image elsewhere into the clipboard and save. 

It worked first time and I tried several times. From opening an image from the file path directly and repeating. From copying the url of an image elsewhere in Stash and as soon after as an image has been updated trying again. To a mixture of from file path saving then to url pasting and saving. From URL pasting and saving to an image directly copied and pasted from clipboard, and they all saved first time. 

I performed the migrations exactly the same on my main Stash as I did this, when I first upgraded to the new Blobs system, I never noticed this.

I removed all my plugins in my main Stash and tried again to see if I got the error and I did. 

Could it be Stash is locking onto the Blobs due to the sheer amount of files and folders in my Blobs folder? I have 289,490 Files, 65,224 Folders

**Comment by elkorol** [comment] 2023-05-05 09:53
I think I found the issue, I had "Custom Performer Image Path" set, I noticed the folder was empty, so I guess the new Blobs systems doesn't use that setting. 

I removed the path string, saved. Closed Stash and opened again and repeated tests and it appears to have solved the issue.

**Comment by WithoutPants** [comment] 2023-05-23 04:52
> I think I found the issue, I had "Custom Performer Image Path" set, I noticed the folder was empty, so I guess the new Blobs systems doesn't use that setting.
> 
> I removed the path string, saved. Closed Stash and opened again and repeated tests and it appears to have solved the issue.

I don't see why having the custom performer image path set would cause this issue, unless it was set to the blobs directory. I'll close this for now, but I'm not exactly sure what happened here.

**Closed by WithoutPants** 2023-05-23 04:52 UTC
Labels: bug report
