### ISSUE TITLE
[Feature] Custom details and/or notes for performers

### ISSUE THREAD

**Issue by dn8sh6HY** [stashapp/stash#897] opened 2020-10-26 14:01 UTC
The ability to create custom details in addition to the defaults (body type, hair color, etc) as well as a notes field.

**Comment by raunmorgan** [comment] 2020-11-23 18:25
Yes I agree this would be a useful feature. I find that the default detail categories are too limited. I would love to add my own.

**Comment by WithoutPants** [comment] 2021-02-02 00:42
Duplicate of #885

**Closed by WithoutPants** 2021-02-02 00:42 UTC
Labels: feature
