### ISSUE TITLE
[Feature] More options for performers social media

### ISSUE THREAD

**Issue by peterpannimmerland** [stashapp/stash#3347] opened 2023-01-06 12:10 UTC
As mentioned in the title. I would like to suggest adding more fields for social media platforms of the performers.

Just like the Instagram or Twitter field, for example.

I'm thinking of links for Onlyfans, TikTok Youtube and one or two more.

thx, greetings

**Comment by DogmaDragon** [comment] 2023-01-06 12:24
Basically a dupe of https://github.com/stashapp/stash/issues/885 and https://github.com/stashapp/stash/issues/703 and https://github.com/stashapp/stash/issues/1868.

**Comment by houstonguy** [comment] 2023-02-07 06:10
According to response to [this pull request: ](https://github.com/stashapp/stash/pull/1959).

This should be solves using a url_type data table, which has at least

* website
* twitter 
* instagram

For my use-case.. tracking web-streamers/OnlyFans/etc. I would want

* chaturbate
* ManyVids
* OnlyFans
* LinkTree

but there are dozens of sites out there and many performers have lots of urls. This is why they use linktree.
So a good solution would both allow the adding of arbitrary URLs per-performer (i.e. url_type: "other") as well as multiple links of a type. (lots of performers have a free OnlyFans, and a 'VIP' Onlyfans).

If I could suggest, it would also nice to be able to list performer emails. Ideally, when an email url_type is used, it would be auto-prefixed with "mailto:" urls. 

If possible, this feature should aim for lots of flexibility, because at one point it looked like OnlyFans was going away, and many performers went to Fansly and never returned. Twitter looks like it could be dead in a year, so the only thing that is 100% certain about urls is that they will eventually break, and as long as a performer is still living and working, and the Internet remains at least somewhat functional, they will find a new place to host their content... so flexibility here makes Stash future-proof.

**Comment by jtjb07** [comment] 2023-12-14 14:49
> So a good solution would both allow the adding of arbitrary URLs per-performer
Another use case is that many performers have multiple accounts on the same website due to the threat of getting banned. On TikTok especially, it's not uncommon for somebody to have a handful of accounts.

**Comment by feederbox826** [comment] 2024-08-19 04:38
closed by https://github.com/stashapp/stash/pull/4958 with generic URLs field

**Closed** 2024-08-19 04:44 UTC
Labels: feature request
