### ISSUE TITLE
[Bug Report] Scrape with URL in Identify does not set cover

### ISSUE THREAD

**Issue by Nyasume** [stashapp/stash#2474] opened 2022-04-04 21:06 UTC
**Describe the bug**
When using "Scrape with URL" in Identify the cover is not being set.

**To Reproduce**
1. Go to scenes
2. Select 1 scene
3. Click Identify
4. In sources select only "Scrape with URL"
5. Check "Set cover images"

**Expected behavior**
The cover should be updated after identifying

**Screenshots**
![image](https://user-images.githubusercontent.com/8061587/161631478-cdf2e6be-1016-4b66-bb4c-649b5f758ae1.png)

**Stash Version: (from Settings -> About):**
v0.13.1-55-g61d9f57c running in Docker

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 99.0.4844.84

**Comment by bnkai** [comment] 2022-04-04 21:27
Are you sure it is not an issue with the specific scraper? A random scene i used identify with worked fine.
Can you go to the scene you tried to identify -> edit -> scrape with -> Scrape With URL and see if you get an image ?
If you dont get an image there then the issue is not from identify.

**Comment by Nyasume** [comment] 2022-04-04 23:03
> Are you sure it is not an issue with the specific scraper? A random scene i used identify with worked fine. Can you go to the scene you tried to identify -> edit -> scrape with -> Scrape With URL and see if you get an image ? If you dont get an image there then the issue is not from identify.

Yeah I get the image when scrapping from the edit page.

**Comment by WithoutPants** [comment] 2022-06-14 03:14
More information is going to be needed. I'm unable to reproduce this.

Entered a scrapable URL to a random scene, ran Identify with Scrape With URL from the Tasks page. Cover image was set as expected.

**Comment by AnyByte** [comment] 2022-06-14 12:52
Still reproducible for me. I think this this is not working for me but working for you because I moved my WSL instance with Stash from one PC to another and in the process thumbnail images got lost somehow. I got thumbnails back by rescanning all the files once again, but they got set to default preview images instead of the custom ones that were there before.

What happened is that Stash still thinks that the thumbnails are custom ones, so it doesn't replace them.

I checked and regenerated default thumbnail for a scene and after that Identify worked as expected. So, the problem is that thumbnail hash got broken or some flag is left unset, so Stash doesn't replace them.

I think there should be an option to force overwrite of the cover while identifying or an option to generate default thumbnails for selected videos (not on detail page so I had to click through them one by one to generate default thumbnails).

**Comment by Nyasume** [comment] 2022-06-14 12:53
Still reproducible for me. I think this this is not working for me but working for you because I moved my WSL instance with Stash from one PC to another and in the process thumbnail images got lost somehow. I got thumbnails back by rescanning all the files once again, but they got set to default preview images instead of the custom ones that were there before.

What happened is that Stash still thinks that the thumbnails are custom ones, so it doesn't replace them.

I checked and regenerated default thumbnail for a scene and after that Identify worked as expected. So, the problem is that thumbnail hash got broken or some flag is left unset, so Stash doesn't replace them.

I think there should be an option to force overwrite of the cover while identifying or an option to generate default thumbnails for selected videos (not on detail page so I had to click through them one by one to generate default thumbnails).

**Comment by scruffynerf** [comment] 2022-07-18 16:47
> an option to generate default thumbnails for selected videos (not on detail page so I had to click through them one by one to generate default thumbnails).

I wrote a scraper to do this very thing.  It'll be added to the CommunityScraper repo soon.  Select multiple scenes you wish to regenerate thumbnail on, invoke Identify from ... menu, select regeneratethumbnail scraper, and it rebuilds those.  Potentially, you could make it generate non-default ones (ie some fixed time in the scene) by mucking with graphql code, if you wished to grab a particular time stamp in multiple videos. (Like a opening title card, for example)

**Comment by Maista6969** [comment] 2024-01-17 15:50
Probably fixed in #3661 along with the aforementioned #3657

**Closed** 2024-01-17 22:31 UTC
Labels: bug report, not-reproducible
