### ISSUE TITLE
[Feature] Studio Tags

### ISSUE THREAD

**Issue by GsMumbo** [stashapp/stash#1287] opened 2021-04-11 23:29 UTC
**Is your feature request related to a problem? Please describe.**
As you start adding more and more studios, it’s hard to keep track of them all. Most studios have some kind of niche. Amateur, MILF, Reality, etc. It would be great to be able to tag them, thus allowing the user to filter down to all studios that cater to a certain niche.

**Describe the solution you'd like**
Add tags in a similar / equal setup to scenes, images, galleries, performers, etc.

**Additional context**
I think this would be the last major object that doesn’t currently have tags. Wrapping this up would be a huge step for the app.

**Comment by WithoutPants** [comment] 2024-02-23 03:55
This is a duplicate of #2497 and although this issue was created first, it has the bounty assigned to it. Closing this in favour of that.

**Closed by WithoutPants** 2024-02-23 03:55 UTC
