### ISSUE TITLE
[Feature] Performers Organized Button

### ISSUE THREAD

**Issue by cv702** [stashapp/stash#1366] opened 2021-05-04 19:50 UTC
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add "Organized" button for performers similar to Scenes "Organized" button

**Describe alternatives you've considered**
Tags

**Additional context**
N/A

**Comment by DogmaDragon** [comment] 2024-09-24 18:15
Duplicate of https://github.com/stashapp/stash/issues/1170

**Closed by DogmaDragon** 2024-09-24 18:15 UTC
