### ISSUE TITLE
[Bug Report] If no ethnicity is set on freeones a GraphQL error is thrown during scrape

### ISSUE THREAD

**Issue by halorrr** [stashapp/stash#502] opened 2020-04-26 17:05 UTC
**Describe the bug**
Attempting to scrape the pornstar "JC Simpson" from Freeones returns a `Error: GraphQL error: Internal system error. Error <unknown ethnicity>`

**To Reproduce**
1. Click New performer
2. Click "Scrape with..."
3. Enter `JC Simpson`
4. Click "Scrape"
5. Error should pop up

**Expected behavior**
Scraping would not throw a GraphQL error

**Screenshots**
![](https://user-images.githubusercontent.com/1358708/80314272-839f1b80-87be-11ea-8b89-c38c5d622648.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.15.4
 - Chrome
 - Version 81.0.4044.122 

**Additional context**
Issue seems to be that it doesn't know how to handle the case of an ethnicity not being set on freeones. Shown in the profile for that model here https://www.freeones.com/html/j_links/bio_JC_Simpson.php

**Comment by bnkai** [comment] 2020-04-27 07:40
You are probably using the stable version
[fix](https://github.com/stashapp/stash/commit/82201e23e023d0ac5816cca58c59d2f3f1e6660e) is already commited and running in the dev version<https://github.com/stashapp/stash/releases/tag/latest_develop>

**Comment by WithoutPants** [comment] 2020-04-29 02:24
Unable to reproduce. Assuming that you're using the 0.1 build. This has been fixed in the dev version and will be included in the 0.2 release.

**Closed by WithoutPants** 2020-04-29 02:24 UTC
Labels: help wanted
