### ISSUE TITLE
[Feature] Allow usage of hardware acceleration when transcoding

### ISSUE THREAD

**Issue by HASJ** [stashapp/stash#749] opened 2020-08-18 16:14 UTC
**Is your feature request related to a problem? Please describe.**
My CPU is very old but my GPU isn't. I'd much rather use FFmpeg with hardware acceleration for video encoding.

**Describe the solution you'd like**
Allow FFmpeg to be ran with `-c:v h264_nvenc` or `-c:v hevc_nvenc` arguments when transcoding.

**Describe alternatives you've considered**
N/A

**Additional context**
My CPU converts 2160p videos to HEVC at 3 FPS using the Ultrafast preset, resulting in very discernible quality loss. My GPU converts the same video to HEVC at 60 FPS using the Slow preset and I can't see the difference.

**Comment by bnkai** [comment] 2020-08-18 20:41
Duplicate of #305.
Closing.

**Closed** 2020-08-18 20:41 UTC
