### ISSUE TITLE
v0.6.0 and Docker - White screen

### ISSUE THREAD

**Issue by flightsim73** [stashapp/stash#1245] opened 2021-03-29 17:26 UTC
On v0.6.0 using Docker latest tag, I'm only getting a white screen. I get the login screen and then the database migration, which appears to work successfully and then just a blank screen. I also did a fresh install and it goes straight to a white screen.

**Comment by bnkai** [comment] 2021-03-29 17:27
duplicate of <https://github.com/stashapp/stash/issues/1242>

**Comment by bnkai** [comment] 2021-03-29 17:28
closing and stealing your title :-)

**Closed by bnkai** 2021-03-29 17:28 UTC
