### ISSUE TITLE
[Feature] Ability to save video filters on a per scene basis

### ISSUE THREAD

**Issue by neru2132** [stashapp/stash#5293] opened 2024-09-23 20:34 UTC
**Is your feature request related to a problem? Please describe.**
Sometimes there are video files with obvious presentation flaws that can be fixed by a simple filter. One such example would be letter-boxed video (e.g. 16:9 video in a 4:3 container) which can be fixed by setting the appropriate value on the `Scale` slider. This works great in Stash already but the problem is that you have to set the value every time you're watching the video which can be quite cumbersome.

**Describe the solution you'd like**
The ability to save the current video filter settings for any given scene as default.

**Describe alternatives you've considered**
- A global set of video filters which can optionally be applied to (a set of) scenes. From the `Filter` tab, you would be able to add your current settings to this global list if these exact settings are not already included.
- In some cases re-encoding the video might be an alternative but that usually incurs a quality penalty.

**Additional context**
This type of per scene setting could be seen in the same vain as #4168.

**Comment by DogmaDragon** [comment] 2024-09-24 00:15
Duplicate of https://github.com/stashapp/stash/issues/4345

**Closed by DogmaDragon** 2024-09-24 00:15 UTC
Labels: feature request
