### ISSUE TITLE
Clicking back in browser also scrolls to top of the page every time

### ISSUE THREAD

**Issue by victorhooi** [stashapp/stash#1451] opened 2021-05-28 20:53 UTC
**Describe the bug**
If you click back in your browser, the Stash app goes back *and* also scrolls to the top of the page - which is now what you want.

**To Reproduce**
1. Click on a video.
2. Go "Back" in your browser

**Expected behaviour**
The browser should go back one page.

**Screenshots**

**Stash Version: (from Settings -> About):**
v0.7.0-33-gc70faa2a

**Desktop (please complete the following information):**
Reproduced on both Safari and latest Chrome on macOS.

**Additional context**

**Comment by victorhooi** [comment] 2021-05-28 20:55
Discussed in Discord here - https://discord.com/channels/559159668438728723/559159668912553989/847939383134126100

User mentioned it might be a regression associated with:

#1267

**Comment by GsMumbo** [comment] 2021-05-29 03:34
Duplicate of #1442

**Comment by WithoutPants** [comment] 2021-06-26 02:08
Closing as duplicate.

**Closed by WithoutPants** 2021-06-26 02:08 UTC
Labels: duplicate
