### ISSUE TITLE
[Feature] Tag Performers in Markers

### ISSUE THREAD

**Issue by hurricaneporter** [stashapp/stash#2568] opened 2022-05-06 21:28 UTC
**Is your feature request related to a problem? Please describe.**
With multi-scene files, it is harder to identify individual performers. Using markers as a way to divide up multi-scene files into pseudo-scenes is easier, but not all functions available to mark a scene are available in markers.

**Describe the solution you'd like**
Add more scene fields as options to markers, including Performers. Adding end-timestamps to markers would also be helpful.

**Describe alternatives you've considered**

- Breaking up large files into smaller files manually
- Using the Movie editor to #2567 and add begin-end timestamp markers to scenes

**Comment by neru2132** [comment] 2024-11-02 02:16
I think this might be a duplicate of #765.

**Comment by DogmaDragon** [comment] 2024-11-03 02:36
Multipart request.

Duplicate of https://github.com/stashapp/stash/issues/765
Duplicate of https://github.com/stashapp/stash/issues/3147

**Closed by DogmaDragon** 2024-11-03 02:36 UTC
Labels: feature request
