### ISSUE TITLE
Native HEVC/x265 support

### ISSUE THREAD

**Issue by seducingbits** [stashapp/stash#31] opened 2019-03-21 18:42 UTC
x265 is the future. smaller file size by same quality. Or better quality by same file size :)

Right now I noticed that Stash supports x265 by transcoding the files to x264. For example, one of my files is ~3 GB at x265. The x264 transcode came out to be arounf ~ 9 GB, and it looked worse :/

**Comment by StashAppDev** [comment] 2019-03-21 19:04
I agree that x265 is great, the problem is [browser support](https://caniuse.com/#feat=hevc).  Both Chrome and Firefox have said that they will not support HEVC in their browsers, which means those types of files will always require transcoding in order to play properly in Stash.  I suppose you could compile a custom version of Chrome, but the average user is not going to do that.

The future of video on the web is really with the [AV1 codec](https://caniuse.com/#search=av1).  It's still pretty early, but all major browsers will support it.  The problem with this though is the encoding process is very resource intensive since there doesn't exist a hardware encoder for it yet.  I do want to replace x264 with AV1 for better file sizes and quality, but I think it's still too early.  I suppose I could add the option so the user can decide.

This still doesn't really solve the issue with HEVC though, but I don't think there is anything I can do.  Anyone have any ideas?

**Comment by seducingbits** [comment] 2019-03-21 19:51
Bummer! Did not knew that. But AV1 sounds great, haven't seen that in the wild yet, probably for the missing hardware encoding you mentioned.
What about live transcoding of x265? This works great for me with Plex.

**Comment by bnkai** [comment] 2019-03-22 15:08
I have also a lot of x265 and own encodes but browser support is a problem.

If you want to  try webm and vp9 is ok as long as you stick to 8bit encoding and firefox , chrome
and even android browsers work fine with stash and webm.
The compression level is almost the same with x265 but a little slower for the same quality.
I just batch encode my downloads wth ffmpeg and then just let stash handle the compressed webm files.

**Comment by StashAppDev** [comment] 2019-03-22 20:56
I already use webm / vp9 for some of the generated files, so it shouldn't be a stretch to use that for the transcodes.  I'll work on providing some configuration options so that you can choose the encoding parameters rather than how it's hard coded right now.

As for live transcoding, that's something I'd need to build support for.  Doable, but no ETA.

**Comment by ExceptionalError** [comment] 2019-03-27 06:13
Live transcoding is possible with [ffmpeg](https://trac.ffmpeg.org/wiki/StreamingGuide), too.
I am not sure how to consume the stream on the webpage though ...

**Comment by WithoutPants** [comment] 2019-10-18 06:54
Is this resolved now with the live transcoding? @Leopere @bnkai

**Comment by ExceptionalError** [comment] 2019-10-18 07:17
It does play but the player is very sluggish - also seeking does not seem to work.

**Comment by bnkai** [comment] 2019-10-18 19:02
Ffmpeg reencodes to webm vp9 so it depends on your cpu and the scene resolution.
Vp9 on 1080p resolutions can be very demanding even with lower quality settings.

Seeking works also fine since the liveseek PR with the video.js player
The only thing not working is the sprites bar underneathe the player moving along from the start and not the current seek position

**Comment by Leopere** [comment] 2019-10-24 18:27
@WithoutPants I would imagine it should be as this issue was directly related to HEVC/x265 support which was resolved with #79 and #84 I imagine.  However, this feels far from finished at the moment so perhaps a fresh issue is due. Anyone in this thread could author a new issue in regards to any elaborations on this feature.

**Closed by Leopere** 2019-10-24 18:27 UTC
Labels: feature
