### ISSUE TITLE
[Feature] Cumulative options filter

### ISSUE THREAD

**Issue by Gouvernathor** [stashapp/stash#4111] opened 2023-09-12 00:51 UTC
![image](https://github.com/stashapp/stash/assets/44340603/c8999d43-1a01-4ec8-bdb4-a22bb1d86bc4)

The buttons here are round, forcing me to choose only one option. I would like to be able to select several options and see the performers (in this case) which satisfy any of the provided options (in this case where it's mutually exclusive).

**Comment by DingDongSoLong4** [comment] 2023-09-12 06:05
I believe this is a duplicate of #2593.

**Comment by Gouvernathor** [comment] 2023-09-12 09:26
The example is, but my request is more general and not restricted to gender

**Comment by DingDongSoLong4** [comment] 2023-09-12 15:28
Alright, which filter criteria are you referring to then? Most of the criteria support choosing multiple options - the only one I can think of that doesn't is the "Is Missing" criteria, but that is slowly being phased out for more specific criteria.

**Comment by Gouvernathor** [comment] 2023-09-12 17:27
After examination three other cases come up :
- Is missing which you covered
- Resolution but it could also be done adding a "is between" and "is not between" as for Rating
- Captions

**Closed** 2024-09-03 20:09 UTC
Labels: feature request
