### ISSUE TITLE
[Bug Report] Saved filter does not URL decode values when used

### ISSUE THREAD

**Issue by 7dJx1qP** [stashapp/stash#1819] opened 2021-10-09 16:10 UTC
**Describe the bug**
Saved filters with values that have URL encoded characters don't get URL decoded when the saved filter is used. This causes the filter to use a different value than the one it was saved with.

**To Reproduce**
1. Go to Scenes
2. Save a "Title includes +" filter
3. Select the saved filter
4. The filter will display "Title includes %2B" and scenes will be filtered by 2b rather than +

**Expected behavior**
Loading a saved filter should show and use the same values that it was saved with.

**Screenshots**
Original filter ![image](https://user-images.githubusercontent.com/38586902/136665570-e5a34ec0-d442-4fc3-95f3-43be49aef07b.png)
Saved filter ![image](https://user-images.githubusercontent.com/38586902/136665580-32c54a70-c916-44ab-90f6-a2da72a955d4.png)

**Stash Version: (from Settings -> About):**
Version: | v0.9.0
Build hash: | a73c99a6

**Additional context**
Refreshing the page applies the filter correctly and shows the correct value so the problem is just with the initial load of the saved filter.

**Comment by kermieisinthehouse** [comment] 2021-10-09 20:52
Can reproduce

**Comment by kermieisinthehouse** [comment] 2021-10-10 00:07
This looks like two separate bugs, but I haven't completely investigated yet. Deserializing the filters from the url (Models/list-fitler/Filters.tsx) is parsed differently than deserializing them from a saved query (components/List/SavedFilterList.tsx), but both are incorrect. 

This also caught my eye:
```
public makeQueryParameters(): string {
    return queryString.stringify(this.getQueryParameters(), { encode: false });
  }
```

**Comment by DampToast** [comment] 2022-02-08 06:14
I have a fix for this locally and will submit it tomorrow via a PR.

**Closed** 2022-02-10 01:49 UTC
Labels: bug, help wanted, bug-verified, ui
