### ISSUE TITLE
[Feature] Get a list of scenes from stashdb that I do not have.

### ISSUE THREAD

**Issue by ghost** [stashapp/stash#2092] opened 2021-12-07 17:54 UTC
Given a performer or studio get a list of scenes with them from stash-box that I do not have in my stash collection.

**Comment by millatime1010** [comment] 2021-12-07 18:58
There is currently a chrome extension that does something similar to what you are asking, that you may use in the meantime. [https://github.com/millatime1010/stashdb-extension](url). From the stashdb page it will show you which scenes are in your stash collection.

**Comment by z8r8xsmbxciryzv3g46j** [comment] 2021-12-07 20:14
I got the idea from your extension. It was something that might be worth adding to stash anyway.

**Comment by feederbox826** [comment] 2024-08-19 04:00
Duplicate of #2264, taking that one since it has more discussion

**Closed** 2024-08-19 04:05 UTC
Labels: duplicate
