### ISSUE TITLE
[RFC] URLs array for performers

### ISSUE THREAD

**Issue by xx790** [stashapp/stash#3158] opened 2022-11-19 19:36 UTC
# URLs array for performers

### Scope

Currently a performer profile can only contain a single URL + Twitter + Instagram.
There is no other way to have clickable links in profile as well.
This is very inflexible and doesn't reflect performers online presence well.
Stash should be able to collect any links from scrappers.

##  Long Form

- performers publish content on multiple sites;
- there are multiple sites that maintain performers information;
- there are multiple tube sites with performer profiles;
- there are more than two social network sites;
- performers may have one and more official sites.

Having specific fields in the database for each website would be a futile effort. Not being able to store some of them puts the limit on the usefulness of the performer profile.
Having a markdown or at least a limited markup in the description field would allow to circumvent the issue but would not allow to extract links information easily when needed (for example, in order to update information from scrapers).

Scrapers should be able to provide URLs array with any number of entries. Performer profile will accumulate unique urls.

Urls stored in performer profile should be available for scraping if corresponding scraper is available.

Backwards compatibility:
When legacy code provides URL, Twitter, Instagram fields - they can be added to URLs list if not existed there already.
When providing objects to legacy code - Twitter url, Instagram url and the first url can be extracted from the URLS list and set as legacy fields.

## Examples

Some links for a single random performer:
```
https://www.s1s1s1.com/actress/detail/1016835/
https://www.freeones.com/ayami-syunka
https://www.javlibrary.com/en/vl_star.php?s=azbay
https://www.boobpedia.com/boobs/Shunka_Ayami
https://www.babepedia.com/babe/Syunka_Ayami
https://www.imdb.com/name/nm7714883
https://www.reddit.com/r/ShunkaAyami/
https://jpop.fandom.com/wiki/Ayami_Shunka
https://syunka-ayami.blog.jp/
https://twitter.com/ayami_syunnka
https://instagram.com/ayami_syunnka0815
```

**Comment by 7dJx1qP** [comment] 2022-11-19 19:52
There's an open feature request for multiple performer URLs https://github.com/stashapp/stash/issues/703 and it is planned for v0.19.0

**Comment by xx790** [comment] 2022-11-19 20:01
Hmm. Sad that solution seems half-assed (doesn't make it unified with existing fields - I don't want to manage "main" url, Twitter, Instagram - I want them to be automatically migrated into the new system). And I can't see whether it will work nice with scrapers.

**Comment by WithoutPants** [comment] 2022-11-20 23:00
Duplicate of #703. Design/implementation yet to be finalised.

**Closed by WithoutPants** 2022-11-20 23:00 UTC
Labels: help wanted
