### ISSUE TITLE
[Feature] Search Bar at Top of Each Page

### ISSUE THREAD

**Issue by Psaucer45** [stashapp/stash#3623] opened 2023-03-31 12:43 UTC
A search bar at the top of each webpage to allow quickly finding scenes, movies, performers, etc. It would have autocomplete predictive capabilities.
[
![IMG_3754](https://user-images.githubusercontent.com/129516945/229123155-c720e9cc-7318-495e-b4e7-986045ad8c21.jpeg)
](url)

**Comment by DogmaDragon** [comment] 2023-03-31 12:50
Dupe of https://github.com/stashapp/stash/issues/1152

**Closed** 2023-03-31 12:50 UTC
Labels: feature request, duplicate
