### ISSUE TITLE
[Feature] Add optional end timestamp to markers.

### ISSUE THREAD

**Issue by skier233** [stashapp/stash#5054] opened 2024-07-07 00:48 UTC
**Is your feature request related to a problem? Please describe.**
Adding an end timestamp to markers would be very beneficial for several reasons:

1. Seeing when a marker ends
2. With an end timestamp to markers, it allows creating "compilations" of multiple markers of all a certain type.
3. With end timestamps to markers, it would be possible to query scenes that have a total duration of markers with a certain tag (doesn't have to be implemented at the same as these changes). You could for example search for scenes with >27s of "Tag A".

**Describe the solution you'd like**
An optional end timestamp value on markers. If the end timestamp is set then watching a marker in the "markers" page would show the marker from the start to the end timestamp and we could use the queue functionality to chain markers back to back to make compilations.

**Describe alternatives you've considered**
Not a great alternative right now for this usecase.

**Comment by DogmaDragon** [comment] 2024-07-07 12:27
Duplicate of https://github.com/stashapp/stash/issues/3147.

**Closed by DogmaDragon** 2024-07-07 12:27 UTC
Labels: feature request, duplicate
