### ISSUE TITLE
[Bug Report] Performer age filter 'less than' is broken

### ISSUE THREAD

**Issue by QxxxGit** [stashapp/stash#3783] opened 2023-05-29 05:33 UTC
Ran into the issue when I tried filtering for performers age < 25, and I was getting results for performers over 30. I think this is the only filter of the set with this issue. I believe this is a backend issue, as I ran a query in GQL and it returned bad results too. 

I'm using the latest commit 1c59d91

**Comment by DogmaDragon** [comment] 2023-05-29 06:02
Reproduced on <https://github.com/stashapp/stash/commit/e685f80e3dd2575e7458302dbe63693aca7acfb9>. It's weird that it excludes some but not all performers over the that doesn't match the filter. 

Same issue occurs on Performers > Age filter.

**Comment by MrX292** [comment] 2023-05-29 13:20
seams to be caused by a Death Date of 0001-01-01 which the ui does not show, but i can filter for it in stash.

**Comment by dogwithakeyboard** [comment] 2023-05-29 20:11
As mentioned in Discord my affected performer records had updated at dates that fall between the v18.0 and v19.0.

**Comment by WithoutPants** [comment] 2023-06-06 22:26
Fixed by #3222

**Closed by WithoutPants** 2023-06-06 22:26 UTC
Labels: bug
