### ISSUE TITLE
[Bug Report] Movies are filtered for uniqueness based on title alone

### ISSUE THREAD

**Issue by Darklyter** [stashapp/stash#4839] opened 2024-05-14 21:53 UTC
Not sure if this is a bug or a design choice, but currently movies are tested for uniqueness based on title alone.  With how many movies are available, this leads to quite a number of collisions between studios (and even the same studios across multiple years)

Currently the only way around this is to tweak the title to be something like "This Fine Movie (2021)", but even this can run into collisions and disallow movie creation.

Uniqueness needs to be determined by a combination of title and at minimum year, preferably title/year/studio

I'm putting this into bug reports because it feels more like an oversight instead of an actual choice

**Comment by WithoutPants** [comment] 2024-05-16 05:10
Duplicate of #2042

**Closed by WithoutPants** 2024-05-16 05:10 UTC
Labels: bug report
