### ISSUE TITLE
[Bug Report] Saved views lost when upgrading to stash v0.23.0

### ISSUE THREAD

**Issue by Dark-Obsidian** [stashapp/stash#4196] opened 2023-10-12 09:37 UTC
### Summary
After upgrading to stash v0.23.0 all saved filters that were previously configured were deleted

### To Reproduce
1. Install stash v0.22.0
2. Configure a filtered view in: scenes, performers, tags (these are known to be affected but other may also be)
3. Save the filtered view
4. Upgrade to stash v0.23.0
5. Upgrade the stash DB to schema v48
6. Saved filters are no longer shown

### Expected behaviour
Saved filters persist when upgrading between versions

### Stash Version
v0.22.0 --> v0.23.0

### Desktop information
 - OS: Windows 11
 - Browser: Edge
 - Browser version: Version 114.0.1823.51

***

### Version History
**2032-10-12:** Updated after initial posting to clarify this issue is about *saved filters*

**Comment by xantror** [comment] 2023-10-12 09:39
I still have my saved filters after the upgrade... Think this might only happen in some cases?

**Comment by Dark-Obsidian** [comment] 2023-10-12 10:06
Hmm, that's interesting, am glad it doesn't affect everyone at least!... In my case, the views have definitely gone and have had to begin the process of re-creating them.

As a side note: I did ponder why the views had gone, as I vaguely recall seeing some info about views in the `config.yml` (i.e. **outside the DB**) but wasn't sure about this / thought it might be the *default* view only, not all saved views... 

❓ Can someone confirm where saved views are saved please?

**Comment by WithoutPants** [comment] 2023-10-12 10:11
There's a bit of ambiguity in the language here. By saved views, do you mean saved filters? ie filters that appear in the drop-down list in the scenes/images/etc pages? Saved views could also apply to the front page views.

Saved filters are stored in the database. Front page views are stored in the `config.yml` file.

Have you actually (re-)reproduced this using the steps outlined in the description, or is this just your experience from your production system? Could also try re-migrating from the database file backup.

**Comment by Dark-Obsidian** [comment] 2023-10-12 10:22
@WithoutPants -- Ah OK, apologies I didn't realise about the two terms -- yes, the issue is about ***saved filters***

I haven't reproduced explicitly, however the steps listed are essentially what I have done over the last 24 hours.

I had forgotten about stash backing-up the DB, and so was thinking it was too late to replicate now - I can try and replicate explicitly but could get slightly messy, as am thinking I would need to downgrade stash to v0.22.0 too?

Please can you confirm the rollback process:
- I know there are several warnings about not just copying the `.sqlite` file, so assume I would use the `Restore/Import Database` option in settings?
- Presumably I also need to downgrade stash to v0.22.0?
- If so, do I do this before or after the DB restore?
- I have version control on `config.yml` - does this need to be rolled-back too?

**Comment by WithoutPants** [comment] 2023-10-12 10:28
Depending on your setup, you could create an entirely new stash system in a separate location, for the purposes of testing. You can then copy over your backup sqlite file to the new location, start stash and it will prompt to migrate the system. Alternatively, you can follow your reproduction steps with a new stash system, but I suspect that it might be something specific to your system, and it may not be reproducible from scratch.

**Comment by Dark-Obsidian** [comment] 2023-10-12 10:36
Cool, that might be the easiest option as since my last comment, I also remembered that I have matched several scenes, created new performers, etc [all of which I would lose when downgrading].

In fairness, I wanted to flag this believing it was an issue that would also affect all users but if no-one else reports this and it ends up being is just me, am happy to close this in a few days...
- **If others report**: I will follow your advice above
- **If others don't report**: I have already re-created some of the saved filters I lost and it will probably take me less time to create the remaining saved filters then replicate the issue, so will just ignore/close issue

**Comment by WithoutPants** [comment] 2023-10-12 10:39
If you know your way around the sqlite client, you could also query the `saved_filters` table and send the output here or on Discord, and I can test migrating them myself. I can't think of why they'd have disappeared completely though. Very odd.

**Comment by Dark-Obsidian** [comment] 2023-10-12 11:00
Cool, yeah am happy to do that -- I need to do some other stuff right now, but will post an update later tonight/tomorrow.

Thanks @WithoutPants and @xantror for your help on this!

**Comment by Dark-Obsidian** [comment] 2023-10-12 17:18
Hmm, so that was interesting!...

Please see the below screenshots of various SQL backups, and the live SQL DB...

### Backup: 10 Oct 2023 -- multiple `saved_filters` defined
![stash-go sqlite 48 20231010_014655](https://github.com/stashapp/stash/assets/140384474/2cf15854-17aa-4a20-8b65-92045b97d304)
File: `stash-go.sqlite.48.20231010_014655`

***

### Backup: 11 Oct 2023 -- `saved_filters` table empty!
![stash-go sqlite 48 20231011_112322](https://github.com/stashapp/stash/assets/140384474/e5aa0fed-e253-49f9-a7dd-afccc72d3967)
File: `stash-go.sqlite.48.20231011_112322`

***

### Live: 12 Oct 2023 -- all `saved_filters` now back! (except tags)
![stash-go sqlite](https://github.com/stashapp/stash/assets/140384474/acb3fa6e-e16e-43d8-b3a2-29f8e902db03)
File: `stash-go.sqlite`

***

### Summary
- I opened stash in the browser and can confirm that my saved filters are showing again! 🎉 (even more than I remember manually re-creating TBH, but hey)...
   - It's possible I had simply re-created more than I thought
   - It's also possible that somehow stash re-created them (although this would be a bit odd, given the `saved_filters` table was empty in the last backup)
- Am not entirely sure what happened but if no-one else has experienced anything similar, and from the looks of it I literally just need to create 1 more saved filter to get back to where I was... then happy to close
- Any final thoughts / ideas / comments?

**Side note:** I'm assuming the entries with no name are the default views, correct?

**Comment by WithoutPants** [comment] 2023-11-28 23:08
Closing as I don't think anyone else has had this issue, and I'm not sure what the root cause was.

**Closed by WithoutPants** 2023-11-28 23:08 UTC
Labels: bug report
