### ISSUE TITLE
[Feature] Studio hierarchy - make it useful

### ISSUE THREAD

**Issue by DDC12** [stashapp/stash#1349] opened 2021-04-28 09:58 UTC
**Is your feature request related to a problem? Please describe.**
The problem basically is: What does creating a hierarchy actually do at the moment? The only effect it seems to have, is make an extra studio for every group of studios I had before so I can link them to a parent.

I've tried applying it to studios that have multiple sites. For example Reality Kings who has "RK Prime", "Look At Her Now" and "Dare Dorm", to name a few at random. In my 'old' setup I would make 3 studios:
- "Reality Kings - RK Prime"
- "Reality Kings - Look At Her Now"
- "Reality Kings - Dare Dorm"

Now I'd make a "Reality Kings" studio, with 3 child studios: "RK Prime", "Look At Her Now" and "Dare Dorm". But the only thing I achieved is that I now have 4 studios instead of 3, and it isn't helping me in any way. The Scenes page still contains all studios, but now also includes "Reality Kings" with 0 scenes in it. And if I search for "Reality Kings" I will now not find any of the child studios anymore.

**Describe the solution you'd like**
It would be nice if search for studios, it'd consider the parents as well. So searching for "Dare" would only match "Dare Dorm", but searching for "Reality" would match all 4 (parent + 3 children). 

Because I know that querying with hierarchies is annoying and slow, I'd simply add a column to the studios table, for example "hierarchy", and fill that with the "path" of the studio. For example, Dare Dorm's path would be "Reality Kings\Dare Dorm", simply the names of all the studios in the hierarchy separated by a character, a backslash in this example. 
The only time this needs to be calculated is when a studio is saved and either the name or the parent has changed. In that case you have to update this studio's "path" and that of any children (recursively). 

After that, just have the search use the hierarchy column instead of the name column.

The search filter on the Scenes page could use an update as well then. Whenever you filter on studio, an option to "include child studios" would allow to to simply filter on "Reality Kings" and get all the scenes for any of the child studios.

**Describe alternatives you've considered**
I've tried prefixing the child studios with their parent again (e.g. "Reality Kings - RK Prime"), but then I just have the old situation again, with 1 useless extra parent studio.

**Comment by stg-annon** [comment] 2021-04-29 17:09
A somewhat simple solution at the moment might be to automatically include all the children sites with the parent site when using the "Studios Includes" filter

**Comment by gitgiggety** [comment] 2021-05-16 14:36
Duplicate of #851 ?

**Comment by gitgiggety** [comment] 2021-07-04 05:41
> Duplicate of #851 ?

And now that the studio hierarchy filtering has been released in 0.8.0 I guess this is solved?

**Closed** 2023-12-12 19:45 UTC
