### ISSUE TITLE
[Feature] Flag duplicates as false positive in Duplicate Checker

### ISSUE THREAD

**Issue by Muldec** [stashapp/stash#2615] opened 2022-05-24 11:46 UTC
**Is your feature request related to a problem? Please describe.**
When Duplicate Checker  identify two totally different files as a duplicate, there's no way to tell it to skip this association next time it runs. As a result, this false positive appears on each runs and is poluting the results.

**Describe the solution you'd like**
I'd want to be able to click a button saying "Ignore" that can be remembered on future checks to not show those two files as duplicates.

**Describe alternatives you've considered**
Currently ignoring it

**Comment by JediMaster25** [comment] 2023-03-01 08:37
Duplicate of #1656

**Comment by JediMaster25** [comment] 2023-03-01 08:44
If you ignore by mistake some scene there would be no way of getting it back.

This is a way this could be done.
Having a toggle between scenes marked as ignored and the usual list. You select scenes with the checkbox and then ignore all selected scenes and their matches with an `Ignore` button. If you toggle to see the scenes marked as ignored the `Ignore` button should change into a `Restore` button.

**Comment by Teda1** [comment] 2023-03-01 16:05
Closing in place of [#1656](https://github.com/stashapp/stash/issues/1656)

**Closed by Teda1** 2023-03-01 16:05 UTC
Labels: feature request
