### ISSUE TITLE
[Feature] Auto-populate performer when using "Scrape With"

### ISSUE THREAD

**Issue by silembir** [stashapp/stash#1203] opened 2021-03-12 17:21 UTC
Currently, when using "Scrape With" on a performer page, you are required to type in the performer that you want to scrape information for.  This should ideally be auto populated with the current selected performer because I can't see any situation where you would want to scrape details for a different performer than the one you have selected.  Thanks!

![image](https://i.imgur.com/siMDDNK.png)

**Comment by bnkai** [comment] 2021-03-12 17:26
Closing
Duplicate of #775 
and PR already available #1198

**Closed by bnkai** 2021-03-12 17:26 UTC
