### ISSUE TITLE
[Bug Report] Scene card moves position when performer flyout has large amount?

### ISSUE THREAD

**Issue by echo6ix** [stashapp/stash#3567] opened 2023-03-20 20:30 UTC
**Describe the bug**
Hovering over a performer flyout is causing the scene card to move position to the next row, possibly when the performer count is high (in my case 5). I cannot reproduce this with every studio scene tab, just this specific case.

**To Reproduce**
1. Go to Studios > Scenes tab (amount of scenes may be important, so there are 5 scenes listed)
2. Hover over the performers flyout (performer amount may be important, so there are 5 performers listed in the flyout)
3. The scene card moves down to the next row
4. Move mouse off the target, the scene card moves back to original position

**Expected behavior**
The scene card should not move position

**Screenshots**
NSFW https://i.imgur.com/L4Taskd.mp4

**Stash Version: (from Settings -> About):**
v0.19.1-78-g496c3649 (running on Linux)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version 111.0.5563.65 
 - Resolution: 1920x1080 (Scaling set to 125%)

**Comment by dogwithakeyboard** [comment] 2023-05-29 19:59
This is reproducable. It's caused by the flyover being inserted into the body but in the studio page the .content-container div has the scrollbars. When the flyover is inserted into the body and needs more vertical space the body scrollbars appear and take up a little more horizontal space. If everything is positioned just right the card will break into a new row.

**Comment by Gykes** [comment] 2024-09-05 02:49
Per convo with OP in discord it seems like this isn't reproducible anymore. Perhaps it was fixed accidently in some other PR. 

Recommend closing :)

**Closed** 2024-09-05 02:49 UTC
Labels: bug report
