### ISSUE TITLE
[Feature] A/B Looper functionality - the ability to create video snippets

### ISSUE THREAD

**Issue by uemanresu** [stashapp/stash#3340] opened 2023-01-05 01:49 UTC
**Is your feature request related to a problem? Please describe.**
No, it's not related to a problem. 
  
**Describe the solution you'd like**
A feature to create smaller loops on videos would be great! There is a feature in VLC that is exactly what I mean [(described here)](https://superuser.com/a/306155). Something quick and easy would be great. Basically so right while you're watching a video you can quickly make a loop on a specific portion of the video without having to go through the hassle, and use up the disk space, to make another separate video file of the desired clip. Something very similar to the 'Markers' functionality that is currently in Stash - but to make a little "gif" type loop of the larger video.

**Describe alternatives you've considered**
The 'gifs' functionality on PornHub is a similar feature. 

**Additional context**
For example, if I had a video that was five minutes long and I wanted to make a loop of the video from 2:35-2:42. Perhaps it could be incorporated into the 'Markers' section - where you could have a start time and an optional end time to the marker. If there was an end time specified then the video would automatically loop during playback when watching that marker.

**Comment by ghfsa** [comment] 2023-01-10 07:54
I'd add that making that portion properly sorted is equally important for quick recall/viewing.

I guess once that portion is marked, adding it to a Playlist would really help. I think the current Marker section isn't very intuitive, in that it doesn't automatically gives an assorted collection (playlist) of the clips marked.

**Comment by pjsentry** [comment] 2023-05-14 12:16
Would be good if repeat function is integrated with Markers feature. Markers can have an optional "end" timestamp. This way, markers with both "start" and "end" timestamp can be optionally played in loop. This way, looped clips will have all the same features as Markers (tags, title, preview, etc.).

This doesn't mean Markers would be the only way to do an A-B repeat. If the user wants to play a marker clip on loop, it will just prefill the A-B repeat control in the video player.

**Comment by pjsentry** [comment] 2023-05-14 12:26
https://github.com/stashapp/stash/issues/3340 Duplicate

**Comment by DogmaDragon** [comment] 2023-05-14 13:49
Dupe of https://github.com/stashapp/stash/issues/3264

**Closed** 2023-05-14 13:49 UTC
Labels: feature request, duplicate
