### ISSUE TITLE
[Task] Document JSON spec

### ISSUE THREAD

**Issue by StashAppDev** [stashapp/stash#7] opened 2019-02-11 11:40 UTC
https://github.com/stashapp/StashServer/issues/34

https://json-schema.org/

**Comment by yoshnopa** [comment] 2019-05-04 19:38
I took care of that, only thing untested (and therefore maybe not entirely extensive) is the gallery function, of which I have none.

**Comment by yoshnopa** [comment] 2019-05-11 09:41
Tried them as well with a dummy file, there are no jsons created at all of this kind, added it to the documentation.
This issue can be closed.

**Comment by WithoutPants** [comment] 2019-11-17 07:52
Looks like a duplicate of #138

**Closed** 2022-01-29 01:16 UTC
Labels: duplicate
