### ISSUE TITLE
[Feature] Embed URL Videos 

### ISSUE THREAD

**Issue by inject3d** [stashapp/stash#5402] opened 2024-10-19 20:48 UTC
When a user creates a new scene entry the user can specfify a url as front photo plus the video.

If the url is not a direct video it should try to embed the original video player instead of showing a black screen.

Pro is that the user does not need to bookmark the url or that you create an account for the page.

Was that idea already discussed in the past and already withdrawn?

I already saw discussions about using yt dl etc but in the end why download if it is available online?

**Comment by DogmaDragon** [comment] 2024-10-19 20:59
Duplicate of https://github.com/stashapp/stash/issues/3930

**Closed by DogmaDragon** 2024-10-19 20:59 UTC
Labels: feature request
