### ISSUE TITLE
[Feature] Order Scenes by Scene Number Within Movie

### ISSUE THREAD

**Issue by halorrr** [stashapp/stash#805] opened 2020-09-11 13:31 UTC
**Is your feature request related to a problem? Please describe.**
Clicking a movie always shows me the scenes out of order. Example:
![11-27-c1huq-sw88z](https://user-images.githubusercontent.com/1358708/92931360-52438700-f411-11ea-8d9a-596ca8b789df.jpg)

**Describe the solution you'd like**
I'd like the default ordering within a Movie to order the scenes number scene number.

**Describe alternatives you've considered**
Alternatively even sorting them by name as the default would fix the issue for the _majority_ of movies.

**Additional context**
N/A

**Comment by WithoutPants** [comment] 2020-09-11 13:32
Looks like a duplicate of #736

**Closed** 2020-09-11 13:36 UTC
