### ISSUE TITLE
[Feature] Inject Custom JS

### ISSUE THREAD

**Issue by naughty447** [stashapp/stash#2109] opened 2021-12-12 06:55 UTC
**Personal Customization**
I would want to inject my personal js and do a few things differently. Like adding a download button, or opening link in new tab...to name a few.

**Solution**
To be able to provide custom js which would be included on every page. User can create a custom js for the feature or changes that they want personally.

**Comment by naughty447** [comment] 2021-12-12 06:57
Please let me know if there is such a feature already available? Or any folder structure where i could place my js files and they would get loaded automatically.

**Comment by echo6ix** [comment] 2021-12-12 07:00
Already requested here https://github.com/stashapp/stash/issues/1217

> Please let me know if there is such a feature already available?

Not really. You may want to check out out the third reply on this thread https://github.com/stashapp/stash/issues/1217#issuecomment-853759427

**Comment by WithoutPants** [comment] 2021-12-13 00:39
Duplicate of #1217

**Closed by WithoutPants** 2021-12-13 00:39 UTC
Labels: duplicate
