### ISSUE TITLE
[Bug Report] Videos not scanning in

### ISSUE THREAD

**Issue by croachasfu** [stashapp/stash#5422] opened 2024-10-26 19:57 UTC
**Describe the bug**
Videos are being prevented from scanning in by an error

**To Reproduce**
Running any scan that includes a video

**Expected behavior**
New videos should be populated in Scenes

Stash Version: 0.27.2

**Desktop (please complete the following information):**
 - OS: Win10 Home
 - Browser: Firefox 131.0.3 64-bit

Logs:
24-10-26 12:52:12Info    Scan finished (1m8.8848957s)
2024-10-26 12:52:12Error   error processing "C:\\TestFolder\\TestVid (4).mp4": running ffprobe on "C:\\TestFolder\\TestVid (4).mp4": FFProbe encountered an error with <C:\TestFolder\TestVid (4).mp4>.
Error JSON:

Error: exit status 1
2024-10-26 12:52:12Info    Calculating fingerprints for C:\TestFolder\TestVid (4).mp4 ...
2024-10-26 12:52:12Error   error processing "C:\\TestFolder\\TestVid (3).mp4": running ffprobe on "C:\\TestFolder\\TestVid (3).mp4": FFProbe encountered an error with <C:\TestFolder\TestVid (3).mp4>.
Error JSON:

Error: exit status 1
2024-10-26 12:52:12Info    Calculating fingerprints for C:\TestFolder\TestVid (3).mp4 ...
2024-10-26 12:52:12Error   error processing "C:\\TestFolder\\TestVid (2).mp4": running ffprobe on "C:\\TestFolder\\TestVid (2).mp4": FFProbe encountered an error with <C:\TestFolder\TestVid (2).mp4>.
Error JSON:

Error: exit status 1
2024-10-26 12:52:12Info    Calculating fingerprints for C:\TestFolder\TestVid (2).mp4 ...
2024-10-26 12:52:12Error   error processing "C:\\TestFolder\\TestVid (1).mp4": running ffprobe on "C:\\TestFolder\\TestVid (1).mp4": FFProbe encountered an error with <C:\TestFolder\TestVid (1).mp4>.
Error JSON:

Error: exit status 1
2024-10-26 12:52:12Info    Calculating fingerprints for C:\TestFolder\TestVid (1).mp4 ...

**Comment by DogmaDragon** [comment] 2024-10-27 09:30
Duplicate of https://github.com/stashapp/stash/issues/5388

Make sure your Library paths are not read only.

**Closed by DogmaDragon** 2024-10-27 09:30 UTC
Labels: bug report
