### ISSUE TITLE
Deceased Performers

### ISSUE THREAD

**Issue by nathanstreetx** [stashapp/stash#5372] opened 2024-10-13 07:44 UTC
Deceased Symbol. I believe I have seen this raised before, but a symbol to indicate that a performer is deceased, perhaps next to their age? 
![image](https://github.com/user-attachments/assets/6be4c563-9842-4b60-9e96-6c9d7b0fe7c1)

Also can we change the name 'Death Date' to 'Date of Death'. And change the date format (e.g. April 20th, 2016)

![image](https://github.com/user-attachments/assets/3d12f75c-35c7-4c77-8e02-d725348a60db)

**Comment by feederbox826** [comment] 2024-10-13 08:18
duplicate of #5326

**Closed** 2024-10-13 11:16 UTC
Labels: feature request, duplicate
