### ISSUE TITLE
Auto populate performer's name field when scraping.

### ISSUE THREAD

**Issue by JaseNZC** [stashapp/stash#1196] opened 2021-03-11 10:41 UTC
Having the performer field auto populate with the performers name for scraping would make things a lot easier.

**Comment by peolic** [comment] 2021-03-11 11:49
Duplicate of #775?

**Comment by JaseNZC** [comment] 2021-03-11 11:51
> Duplicate of #775?

Indeed it looks like it is.

**Closed** 2021-03-13 23:20 UTC
