### ISSUE TITLE
[Feature] Pass filename to scraper script

### ISSUE THREAD

**Issue by TaylorSwiftFan13** [stashapp/stash#1554] opened 2021-07-04 10:40 UTC
I've been working on a scraper/script that parses filenames. 
However it would be more useful to me if I could get the raw filename of the scene. Currently I can only get the "title" which is usually the filename, but sometimes it's not because I've previously changed it or something.

My .yml looks like this:

```
sceneByFragment:
        action: script
        script:
               	- python
                - 1test.py
```

Reading `sys.stdin.read()` in the python script I get:

`{"clientMutationId":null,"id":"6633","title":"Intriguing title goes here","details":"","url":"","date":"2021-07-03","rating":null,"organized":null,"studio_id":"15","gallery_ids":[],"performer_ids":["119"],"movies":[],"tag_ids":[],"cover_image":null,"stash_ids":[]}`

Would be really useful if it also had a "filename" field which contained the base filename of the video.

I've tried adding `{filename}` (because I saw queryURL can use it) as a parameter to the script like this:
```
sceneByFragment:
        action: script
        script:
               	- python
                - 1test.py
                - {filename}
```

but it errors out:

```
[31mERRO[0m[2021-07-04 12:38:10] Error loading scraper /root/.stash/scrapers/1test.yml: yaml: unmarshal errors:

line 8: cannot unmarshal !!map into string
```

**Comment by gitgiggety** [comment] 2021-07-04 11:18
The error you're getting is related to invalid YAML. This as `{` and `}` are used to open and close objects. You should thus put the value in quotes, so it will be interpreted s string.

```yaml
sceneByFragment:
        action: script
        script:
                - python
                - 1test.py
                - '{filename}'
```

But my guess would be this doesn't work anyway (and will just pass a literal `{filename}` argument) and should be added to the info send to the script using stdin.

**Comment by TaylorSwiftFan13** [comment] 2021-07-04 11:41
> The error you're getting is related to invalid YAML. This as `{` and `}` are used to open and close objects. You should thus put the value in quotes, so it will be interpreted s string.
> 
> ```yaml
> sceneByFragment:
>         action: script
>         script:
>                 - python
>                 - 1test.py
>                 - '{filename}'
> ```
> 
> But my guess would be this doesn't work anyway (and will just pass a literal `{filename}` argument) and should be added to the info send to the script using stdin.

You are correct 

`scraper: ['1test.py', '{filename}']`

**Comment by Tweeticoats** [comment] 2021-07-04 12:07
Unfortunately it does not work that way.
You can specify what script or program you want to use but that only gets the json input ie the "title" value is passed to standard input of your program or script and you need to pass the json, get the title field and do something with that and return json to standard out with your results.

There is a 

I also would find it useful to have the file name passed to scrapers for my xbvrdb scraper as I can better check against known files instead of assuming that the title contains the file name and extension.
If we could have a "sceneByFilename" type of script that passes the file name of the file it would be useful.

**Comment by TaylorSwiftFan13** [comment] 2021-07-04 12:32
Here is a horrible workaround using the scene ID we get to read that row from the sqlite db:

```
import sqlite3, os, json, sys

def debug_print(*s):
    print(*s, file=sys.stderr)

db_file = "../stash-go.sqlite"

frag = json.loads(sys.stdin.read())
scene_id = frag['id']

con = sqlite3.connect(db_file)
cur = con.cursor()
for row in cur.execute("SELECT * FROM scenes where id = " + str(scene_id) + ";"):
    #debug_print(row)
    filepath = row[1]
con.close()

basename = os.path.basename(filepath)
debug_print("base filename: " + basename)
```

**Comment by bnkai** [comment] 2021-07-04 19:29
possible duplicate of #1027

**Closed** 2024-06-11 03:12 UTC
