### ISSUE TITLE
[Bug Report] Cleaning action does not remove empty galleries

### ISSUE THREAD

**Issue by Ijeay** [stashapp/stash#1948] opened 2021-11-03 21:17 UTC
**Describe the bug**
When using the clean function all missing files gets removed but all their galleries remains with 0 pictures. It's possible to remove them one by one but who want to do that with thousands of empty galleries?

**To Reproduce**
1. Go to Configuration
2. Add a Directory with sub-folders that have images.
3. Make sure to Check mark **Create galleries from folders containing images**
4. Do a Scan in task
5. Go to Configuration and remove the Directory.
6. Go to tasks and do a clean
7. You end up with lots of empty galleries

**Comment by kermieisinthehouse** [comment] 2021-11-03 22:13
Duplicate of #1313, but it's a good reminder and I've targeted that one for the release after next.

**Closed by kermieisinthehouse** 2021-11-03 22:13 UTC
Labels: duplicate, help wanted
