### ISSUE TITLE
[Feature] PWA support

### ISSUE THREAD

**Issue by florian-sattler** [stashapp/stash#1742] opened 2021-09-18 17:01 UTC
Please add PWA capabilities to the web frontend. A progressive web app allows users to install the site as an app. This may also be used for caching and to make the interface more responsive. 

To provide the basic ability to install the app, only two short files have to be provided:
1. A web manifest.json
2. A service-worker.js

**Comment by WithoutPants** [comment] 2021-10-03 00:34
Duplicate of #283

**Closed by WithoutPants** 2021-10-03 00:34 UTC
Labels: duplicate
