### ISSUE TITLE
[Feature] Saved Searches / Filters

### ISSUE THREAD

**Issue by GsMumbo** [stashapp/stash#1291] opened 2021-04-12 00:57 UTC
**Is your feature request related to a problem? Please describe.**
If you want to get a fairly specific subset of media, you have to add a few different filters (and usually change the sort too). While it’s great you can do this, as soon as you want to view anything else you have to remove the filters, meaning you have to set them all back up if you want to return to that subset of media. 

tl;dr - Any time you want to filter something, you have to resetup all your filters / sorts.

**Describe the solution you'd like**
A query is already being run to serve up your filter / sort results. Add a “Save Search” button next to the filter area. This will save this query and allow you to set a title. Once saved, there will be a drop down where you can pick which set of filters you want to use (along with an always available “Default” that clears all filters and sorts.

**Describe alternatives you've considered**
Smart Playlists, but that involves setting up a whole new UI and configuration interface. If we can already add all these filters, it makes sense to build it around that feature set.

**Comment by WithoutPants** [comment] 2021-04-12 01:04
Duplicate of #730

**Closed by WithoutPants** 2021-04-12 01:04 UTC
