### ISSUE TITLE
[Bug Report] When adding two filters of the same attribute to scene view, the first one gets ignored

### ISSUE THREAD

**Issue by hyde231** [stashapp/stash#757] opened 2020-08-22 13:53 UTC
**Describe the bug**
The scene list allows to add multiple filters and several different attributes. When adding two or more filters on the same attribute, for example one filter on "tag" including some values and another one on "tag" excluding other values, only the last filter is evaluated and the previous ones are ignored.

Adding filters of different attributes (e.g. tags and ratings) are handled correctly.

**To Reproduce**
1. Go to 'scenes'
2. Click on 'add filter - Tags' 
3. Select 'Inlcudes' and enter a value
4. Click 'Add filter'
5. Add a second filter by clicking on 'add filter' and choose 'Tags' again
6. Select 'excludes' and add a different value than for the first filter
7. Click 'Add filter'
8. Both filters show up, but only the last one gets evaluated and the first one ignored

**Expected behavior**
Expected behaviour would be to handle all filters with AND operator, just like it is working for filters on different attributes

**Stash Version: (from Settings -> About):**
Latest development version on docker
v0.2.1-70-g2cdec6b

**Desktop (please complete the following information):**
 - OS: Win10 64bit
 - Browser FF 79.0 64bit

**Comment by Ronnie711** [comment] 2023-12-29 22:33
Unable to reproduce this behaviour in V24.0 (Windows 11, FF 121). 

This was raised on a docker environment. If someone using Docker can confirm, then this could be closed.

**Comment by scruffynerf** [comment] 2023-12-30 00:50
I don't believe you can do multiple filters like this anymore.  Close it.

**Comment by DingDongSoLong4** [comment] 2023-12-30 12:35
Multiple filters were never really properly supported in the UI, and adding multiple filters like this is indeed no longer possible.

**Closed by DingDongSoLong4** 2023-12-30 12:35 UTC
Labels: bug report
