### ISSUE TITLE
[Feature] Track number of views and most recent view for a video

### ISSUE THREAD

**Issue by dn8sh6HY** [stashapp/stash#898] opened 2020-10-26 14:02 UTC
This would allow for sorting by "most recently viewed"

**Comment by Caleripo** [comment] 2022-01-12 10:16
Duplicate of #633 I think.

**Comment by sleetx** [comment] 2022-01-19 08:45
It would be helpful to sort scenes by most recently viewed. There's already fields for "Created At" and "Updated At"... let's add "Last Viewed At"

There's been some discussion about what qualifies as a "view" for the timestamp and the view counter... does it trigger the instant you open it? If you watch it for 30 seconds, 5 minutes, etc? I think a short delay would be sufficient so it ignores accidental opens.

**Comment by AdultSun** [comment] 2023-04-25 20:34
Completed with PR #3055 which includes a "Last Played At" option for sorting.

**Closed by AdultSun** 2023-04-25 20:34 UTC
Labels: feature
